const en = {
  newChat: 'New chat',
  search: 'Search chats',
  pinned: 'Pinned',
  recent: 'Recent',
  projects: 'Projects',
  memory: 'Memory',
  skills: 'Skills',
  bookmarks: 'Bookmarks',
  automations: 'Automations',
  settings: 'Settings',
  welcome: 'What would you like to do?',
  intro: 'A little help. A lasting memory.',
  prompt: 'Ask Anda anything, or give it something to work on…',
  addProject: 'Add project',
  noChats: 'Your conversations will appear here.',
  archive: 'Archive',
  archived: 'Archived chats',
  restore: 'Restore',
  pin: 'Pin',
  unpin: 'Unpin',
  rename: 'Rename',
  connected: 'Local daemon connected',
  disconnected: 'Daemon disconnected',
  reconnect: 'Reconnect',
  folder: 'Workspace',
  noFolder: 'No workspace',
  general: 'General',
  config: 'Agent configuration',
  theme: 'Appearance',
  language: 'Language',
  system: 'System',
  light: 'Light',
  dark: 'Dark',
  notifications: 'Task notifications',
  login: 'Launch at login',
  runtime: 'Runtime',
  chooseBinary: 'Choose anda executable',
  logs: 'Open logs',
  save: 'Save',
  cancel: 'Cancel',
  close: 'Close',
  create: 'Create',
  refresh: 'Refresh',
  stop: 'Stop task',
  memoryMode: 'Memory for this chat',
  standard: 'Use and save memory',
  noStore: 'Use memory, don’t save',
  off: 'Memory off',
  modelScope: 'Model selection applies to this daemon',
  resources: 'Resources',
  noResources: 'Files and outputs from this chat will appear here.',
  loading: 'Connecting to your local workspace…',
  history: 'Load earlier messages',
  newContent: 'New content below',
  unconfirmed: 'A message may have been accepted. Review the chat before sending again.',
  reviewed: 'I reviewed the chat — allow new messages',
  local: 'Local',
  update: 'Check for updates',
  searchHint: 'Search titles or press Enter to search conversation history',
  schedule: 'Schedule',
  task: 'Prompt',
  name: 'Name',
  interval: 'Interval',
  timezone: 'Time zone',
  pause: 'Pause',
  resume: 'Resume',
  remove: 'Remove',
  noJobs: 'Let Anda take care of the recurring work.',
  newJob: 'New automation',
  runHistory: 'Recent runs',
  nextRun: 'Next run',
  suggestion1: 'Explore a project',
  suggestion2: 'Organize my thoughts',
  suggestion3: 'Review my memory',
  details: 'Details',
  drafts: 'Draft',
  copied: 'Copied',
  emptySearch: 'No matching conversations',
  saveNotice: 'Changes saved'
}
const zh: typeof en = {
  newChat: '新聊天',
  search: '搜索聊天',
  pinned: '置顶',
  recent: '最近',
  projects: '项目',
  memory: '记忆',
  skills: '技能',
  bookmarks: '书签',
  automations: '自动化',
  settings: '设置',
  welcome: '今天想做些什么？',
  intro: '随时帮忙，长久记得。',
  prompt: '向 Anda 提问，或交给它一项工作…',
  addProject: '添加项目',
  noChats: '你的聊天会显示在这里。',
  archive: '归档',
  archived: '已归档聊天',
  restore: '恢复',
  pin: '置顶',
  unpin: '取消置顶',
  rename: '重命名',
  connected: '本地服务已连接',
  disconnected: '服务未连接',
  reconnect: '重新连接',
  folder: '工作目录',
  noFolder: '未选择工作目录',
  general: '通用',
  config: 'Agent 配置',
  theme: '外观',
  language: '语言',
  system: '跟随系统',
  light: '浅色',
  dark: '深色',
  notifications: '任务通知',
  login: '登录时启动',
  runtime: '运行时',
  chooseBinary: '选择 anda 可执行文件',
  logs: '打开日志',
  save: '保存',
  cancel: '取消',
  close: '关闭',
  create: '创建',
  refresh: '刷新',
  stop: '停止任务',
  memoryMode: '本次聊天的记忆',
  standard: '使用并保存记忆',
  noStore: '使用记忆，不保存',
  off: '关闭记忆',
  modelScope: '模型选择对当前服务生效',
  resources: '资源',
  noResources: '本次聊天的文件与输出会显示在这里。',
  loading: '正在连接本地工作空间…',
  history: '加载更早消息',
  newContent: '下方有新内容',
  unconfirmed: '一条消息可能已被受理。请核对聊天后再发送。',
  reviewed: '已核对聊天，允许发送新消息',
  local: '本地',
  update: '检查更新',
  searchHint: '搜索标题，按 Enter 搜索聊天内容',
  schedule: '计划',
  task: '任务提示',
  name: '名称',
  interval: '间隔',
  timezone: '时区',
  pause: '暂停',
  resume: '恢复',
  remove: '删除',
  noJobs: '把重复的工作交给 Anda。',
  newJob: '新建自动化',
  runHistory: '最近运行',
  nextRun: '下次运行',
  suggestion1: '探索一个项目',
  suggestion2: '整理我的想法',
  suggestion3: '查看我的记忆',
  details: '详情',
  drafts: '草稿',
  copied: '已复制',
  emptySearch: '没有匹配的聊天',
  saveNotice: '已保存更改'
}
export type Label = keyof typeof en

export const desktopMessages: Record<string, Record<Label, string>> = {
  en,
  zh_CN: zh,
  fr: {
    newChat: 'Nouvelle discussion',
    search: 'Rechercher',
    pinned: 'Épinglés',
    recent: 'Récents',
    projects: 'Projets',
    memory: 'Mémoire',
    skills: 'Compétences',
    bookmarks: 'Favoris',
    automations: 'Automatisations',
    settings: 'Paramètres',
    welcome: 'Que souhaitez-vous faire ?',
    intro: 'Un peu d’aide. Une mémoire durable.',
    prompt: 'Demandez à Anda ou confiez-lui une tâche…',
    addProject: 'Ajouter un projet',
    noChats: 'Vos discussions apparaîtront ici.',
    archive: 'Archiver',
    archived: 'Discussions archivées',
    restore: 'Restaurer',
    pin: 'Épingler',
    unpin: 'Désépingler',
    rename: 'Renommer',
    connected: 'Service local connecté',
    disconnected: 'Service déconnecté',
    reconnect: 'Reconnecter',
    folder: 'Dossier de travail',
    noFolder: 'Aucun dossier',
    general: 'Général',
    config: 'Configuration de l’agent',
    theme: 'Apparence',
    language: 'Langue',
    system: 'Système',
    light: 'Clair',
    dark: 'Sombre',
    notifications: 'Notifications de tâches',
    login: 'Lancer à la connexion',
    runtime: 'Moteur',
    chooseBinary: 'Choisir l’exécutable anda',
    logs: 'Ouvrir les journaux',
    save: 'Enregistrer',
    cancel: 'Annuler',
    close: 'Fermer',
    create: 'Créer',
    refresh: 'Actualiser',
    stop: 'Arrêter la tâche',
    memoryMode: 'Mémoire de cette discussion',
    standard: 'Utiliser et enregistrer',
    noStore: 'Utiliser sans enregistrer',
    off: 'Mémoire désactivée',
    modelScope: 'Le modèle s’applique à ce service',
    resources: 'Ressources',
    noResources: 'Les fichiers de cette discussion apparaîtront ici.',
    loading: 'Connexion à votre espace local…',
    history: 'Charger les messages précédents',
    newContent: 'Nouveau contenu',
    unconfirmed: 'Un message a peut-être été accepté. Vérifiez la discussion avant de renvoyer.',
    reviewed: 'Discussion vérifiée — autoriser de nouveaux messages',
    local: 'Local',
    update: 'Vérifier les mises à jour',
    searchHint: 'Recherchez un titre ou appuyez sur Entrée pour chercher dans l’historique',
    schedule: 'Planification',
    task: 'Consigne',
    name: 'Nom',
    interval: 'Intervalle',
    timezone: 'Fuseau horaire',
    pause: 'Suspendre',
    resume: 'Reprendre',
    remove: 'Supprimer',
    noJobs: 'Confiez les tâches récurrentes à Anda.',
    newJob: 'Nouvelle automatisation',
    runHistory: 'Exécutions récentes',
    nextRun: 'Prochaine exécution',
    suggestion1: 'Explorer un projet',
    suggestion2: 'Organiser mes idées',
    suggestion3: 'Voir ma mémoire',
    details: 'Détails',
    drafts: 'Brouillon',
    copied: 'Copié',
    emptySearch: 'Aucune discussion trouvée',
    saveNotice: 'Modifications enregistrées'
  },
  es: {
    newChat: 'Nuevo chat',
    search: 'Buscar chats',
    pinned: 'Fijados',
    recent: 'Recientes',
    projects: 'Proyectos',
    memory: 'Memoria',
    skills: 'Habilidades',
    bookmarks: 'Favoritos',
    automations: 'Automatizaciones',
    settings: 'Ajustes',
    welcome: '¿Qué te gustaría hacer?',
    intro: 'Un poco de ayuda. Una memoria duradera.',
    prompt: 'Pregunta a Anda o encárgale una tarea…',
    addProject: 'Añadir proyecto',
    noChats: 'Tus conversaciones aparecerán aquí.',
    archive: 'Archivar',
    archived: 'Chats archivados',
    restore: 'Restaurar',
    pin: 'Fijar',
    unpin: 'Desfijar',
    rename: 'Renombrar',
    connected: 'Servicio local conectado',
    disconnected: 'Servicio desconectado',
    reconnect: 'Reconectar',
    folder: 'Carpeta de trabajo',
    noFolder: 'Sin carpeta',
    general: 'General',
    config: 'Configuración del agente',
    theme: 'Apariencia',
    language: 'Idioma',
    system: 'Sistema',
    light: 'Claro',
    dark: 'Oscuro',
    notifications: 'Notificaciones de tareas',
    login: 'Abrir al iniciar sesión',
    runtime: 'Motor',
    chooseBinary: 'Elegir ejecutable anda',
    logs: 'Abrir registros',
    save: 'Guardar',
    cancel: 'Cancelar',
    close: 'Cerrar',
    create: 'Crear',
    refresh: 'Actualizar',
    stop: 'Detener tarea',
    memoryMode: 'Memoria de este chat',
    standard: 'Usar y guardar memoria',
    noStore: 'Usar sin guardar',
    off: 'Memoria desactivada',
    modelScope: 'El modelo se aplica a este servicio',
    resources: 'Recursos',
    noResources: 'Los archivos de este chat aparecerán aquí.',
    loading: 'Conectando al espacio local…',
    history: 'Cargar mensajes anteriores',
    newContent: 'Contenido nuevo',
    unconfirmed: 'Es posible que se haya aceptado un mensaje. Revisa el chat antes de reenviar.',
    reviewed: 'Chat revisado — permitir mensajes nuevos',
    local: 'Local',
    update: 'Buscar actualizaciones',
    searchHint: 'Busca títulos o pulsa Intro para buscar en el historial',
    schedule: 'Programación',
    task: 'Instrucción',
    name: 'Nombre',
    interval: 'Intervalo',
    timezone: 'Zona horaria',
    pause: 'Pausar',
    resume: 'Reanudar',
    remove: 'Eliminar',
    noJobs: 'Deja las tareas repetitivas a Anda.',
    newJob: 'Nueva automatización',
    runHistory: 'Ejecuciones recientes',
    nextRun: 'Próxima ejecución',
    suggestion1: 'Explorar un proyecto',
    suggestion2: 'Organizar mis ideas',
    suggestion3: 'Revisar mi memoria',
    details: 'Detalles',
    drafts: 'Borrador',
    copied: 'Copiado',
    emptySearch: 'No hay conversaciones coincidentes',
    saveNotice: 'Cambios guardados'
  },
  ru: {
    newChat: 'Новый чат',
    search: 'Поиск чатов',
    pinned: 'Закреплённые',
    recent: 'Недавние',
    projects: 'Проекты',
    memory: 'Память',
    skills: 'Навыки',
    bookmarks: 'Закладки',
    automations: 'Автоматизация',
    settings: 'Настройки',
    welcome: 'Что вы хотите сделать?',
    intro: 'Помощь сейчас. Память надолго.',
    prompt: 'Спросите Anda или поручите ей задачу…',
    addProject: 'Добавить проект',
    noChats: 'Здесь появятся ваши чаты.',
    archive: 'Архивировать',
    archived: 'Архив чатов',
    restore: 'Восстановить',
    pin: 'Закрепить',
    unpin: 'Открепить',
    rename: 'Переименовать',
    connected: 'Локальная служба подключена',
    disconnected: 'Нет подключения',
    reconnect: 'Подключить',
    folder: 'Рабочая папка',
    noFolder: 'Папка не выбрана',
    general: 'Общие',
    config: 'Настройки агента',
    theme: 'Оформление',
    language: 'Язык',
    system: 'Системное',
    light: 'Светлое',
    dark: 'Тёмное',
    notifications: 'Уведомления о задачах',
    login: 'Запуск при входе',
    runtime: 'Среда выполнения',
    chooseBinary: 'Выбрать файл anda',
    logs: 'Открыть журналы',
    save: 'Сохранить',
    cancel: 'Отмена',
    close: 'Закрыть',
    create: 'Создать',
    refresh: 'Обновить',
    stop: 'Остановить задачу',
    memoryMode: 'Память этого чата',
    standard: 'Использовать и сохранять',
    noStore: 'Использовать без сохранения',
    off: 'Память выключена',
    modelScope: 'Выбор модели действует для этой службы',
    resources: 'Ресурсы',
    noResources: 'Здесь появятся файлы этого чата.',
    loading: 'Подключение к локальной среде…',
    history: 'Загрузить предыдущие сообщения',
    newContent: 'Есть новые сообщения',
    unconfirmed: 'Сообщение могло быть принято. Проверьте чат перед повторной отправкой.',
    reviewed: 'Чат проверен — разрешить новые сообщения',
    local: 'Локально',
    update: 'Проверить обновления',
    searchHint: 'Поиск по заголовкам; Enter — поиск в истории',
    schedule: 'Расписание',
    task: 'Задание',
    name: 'Название',
    interval: 'Интервал',
    timezone: 'Часовой пояс',
    pause: 'Приостановить',
    resume: 'Продолжить',
    remove: 'Удалить',
    noJobs: 'Поручите повторяющиеся задачи Anda.',
    newJob: 'Новая автоматизация',
    runHistory: 'Последние запуски',
    nextRun: 'Следующий запуск',
    suggestion1: 'Изучить проект',
    suggestion2: 'Упорядочить мысли',
    suggestion3: 'Просмотреть память',
    details: 'Подробности',
    drafts: 'Черновик',
    copied: 'Скопировано',
    emptySearch: 'Совпадений нет',
    saveNotice: 'Изменения сохранены'
  },
  ar: {
    newChat: 'محادثة جديدة',
    search: 'البحث في المحادثات',
    pinned: 'المثبتة',
    recent: 'الأخيرة',
    projects: 'المشاريع',
    memory: 'الذاكرة',
    skills: 'المهارات',
    bookmarks: 'الإشارات المرجعية',
    automations: 'الأتمتة',
    settings: 'الإعدادات',
    welcome: 'ماذا تريد أن تفعل؟',
    intro: 'مساعدة الآن وذاكرة تدوم.',
    prompt: 'اسأل Anda أو كلّفها بمهمة…',
    addProject: 'إضافة مشروع',
    noChats: 'ستظهر محادثاتك هنا.',
    archive: 'أرشفة',
    archived: 'المحادثات المؤرشفة',
    restore: 'استعادة',
    pin: 'تثبيت',
    unpin: 'إلغاء التثبيت',
    rename: 'إعادة تسمية',
    connected: 'الخدمة المحلية متصلة',
    disconnected: 'الخدمة غير متصلة',
    reconnect: 'إعادة الاتصال',
    folder: 'مجلد العمل',
    noFolder: 'لم يتم اختيار مجلد',
    general: 'عام',
    config: 'إعدادات الوكيل',
    theme: 'المظهر',
    language: 'اللغة',
    system: 'النظام',
    light: 'فاتح',
    dark: 'داكن',
    notifications: 'إشعارات المهام',
    login: 'التشغيل عند تسجيل الدخول',
    runtime: 'بيئة التشغيل',
    chooseBinary: 'اختيار ملف anda التنفيذي',
    logs: 'فتح السجلات',
    save: 'حفظ',
    cancel: 'إلغاء',
    close: 'إغلاق',
    create: 'إنشاء',
    refresh: 'تحديث',
    stop: 'إيقاف المهمة',
    memoryMode: 'ذاكرة هذه المحادثة',
    standard: 'استخدام الذاكرة وحفظها',
    noStore: 'استخدام دون حفظ',
    off: 'الذاكرة معطلة',
    modelScope: 'اختيار النموذج يسري على هذه الخدمة',
    resources: 'الموارد',
    noResources: 'ستظهر ملفات هذه المحادثة هنا.',
    loading: 'جارٍ الاتصال بمساحة العمل المحلية…',
    history: 'تحميل الرسائل السابقة',
    newContent: 'محتوى جديد',
    unconfirmed: 'ربما تم قبول رسالة. راجع المحادثة قبل إعادة الإرسال.',
    reviewed: 'راجعت المحادثة — السماح برسائل جديدة',
    local: 'محلي',
    update: 'البحث عن تحديثات',
    searchHint: 'ابحث في العناوين أو اضغط Enter للبحث في السجل',
    schedule: 'الجدولة',
    task: 'التعليمات',
    name: 'الاسم',
    interval: 'الفاصل الزمني',
    timezone: 'المنطقة الزمنية',
    pause: 'إيقاف مؤقت',
    resume: 'استئناف',
    remove: 'حذف',
    noJobs: 'دع Anda تتولى العمل المتكرر.',
    newJob: 'أتمتة جديدة',
    runHistory: 'عمليات التشغيل الأخيرة',
    nextRun: 'التشغيل التالي',
    suggestion1: 'استكشاف مشروع',
    suggestion2: 'تنظيم أفكاري',
    suggestion3: 'مراجعة ذاكرتي',
    details: 'التفاصيل',
    drafts: 'مسودة',
    copied: 'تم النسخ',
    emptySearch: 'لا توجد محادثات مطابقة',
    saveNotice: 'تم حفظ التغييرات'
  }
}
export function label(language: string, key: Label): string {
  const tag = language.toLowerCase().startsWith('zh') ? 'zh_CN' : language.replace('-', '_')
  const messages =
    desktopMessages[tag] || desktopMessages[tag.split('_')[0]!] || desktopMessages.en!
  return messages[key]
}
