const en = {
  newChat: 'New chat',
  search: 'Search chats',
  recent: 'Recent',
  projects: 'Projects',
  memory: 'Memory',
  skills: 'Skills',
  bookmarks: 'Bookmarks',
  automations: 'Automations',
  settings: 'Settings',
  welcome: 'What would you like to do?',
  intro: 'A little help. A lasting memory.',
  prompt: 'Ask Anda anything, or give it something to work on…',
  addProject: 'Add project',
  noChats: 'Your conversations will appear here.',
  archive: 'Archive',
  archived: 'Archived chats',
  restore: 'Restore',
  pin: 'Pin',
  unpin: 'Unpin',
  rename: 'Rename',
  connected: 'Local daemon connected',
  disconnected: 'Daemon disconnected',
  reconnect: 'Reconnect',
  noFolder: 'No workspace',
  general: 'General',
  config: 'Agent configuration',
  theme: 'Appearance',
  language: 'Language',
  system: 'System',
  light: 'Light',
  dark: 'Dark',
  notifications: 'Task notifications',
  login: 'Launch at login',
  runtime: 'Runtime',
  chooseBinary: 'Choose anda executable',
  logs: 'Open logs',
  save: 'Save',
  cancel: 'Cancel',
  close: 'Close',
  create: 'Create',
  refresh: 'Refresh',
  memoryMode: 'Memory for this chat',
  standard: 'Use and save memory',
  noStore: 'Use memory, don’t save',
  off: 'Memory off',
  modelScope: 'Model selection applies to this daemon',
  resources: 'Resources',
  noResources: 'Files and outputs from this chat will appear here.',
  loading: 'Connecting to your local workspace…',
  history: 'Load earlier messages',
  newContent: 'New content below',
  unconfirmed: 'A message may have been accepted. Review the chat before sending again.',
  reviewed: 'I reviewed the chat — allow new messages',
  local: 'Local',
  update: 'Check for updates',
  searchHint: 'Search titles or press Enter to search conversation history',
  schedule: 'Schedule',
  task: 'Prompt',
  name: 'Name',
  interval: 'Interval',
  timezone: 'Time zone',
  pause: 'Pause',
  resume: 'Resume',
  remove: 'Remove',
  noJobs: 'Let Anda take care of the recurring work.',
  newJob: 'New automation',
  runHistory: 'Recent runs',
  nextRun: 'Next run',
  suggestion1: 'Explore a project',
  suggestion2: 'Organize my thoughts',
  suggestion3: 'Review my memory',
  details: 'Details',
  emptySearch: 'No matching conversations',
  // Workbench and audio panels
  changes: 'Changes',
  terminal: 'Terminal',
  browser: 'Browser',
  newTerminal: 'New terminal',
  chooseProject: 'Select a project folder to open its workbench.',
  empty: 'No changes',
  staged: 'Staged',
  unstaged: 'Working tree',
  stage: 'Stage',
  unstage: 'Unstage',
  commit: 'Commit',
  message: 'Commit message',
  gitHistory: 'History',
  worktrees: 'Worktrees',
  branch: 'New branch name',
  createWorktree: 'Create worktree',
  newTab: 'New tab',
  address: 'Address',
  back: 'Back',
  forward: 'Forward',
  reload: 'Reload',
  find: 'Find',
  open: 'Open',
  audio: 'Audio',
  record: 'Record test',
  stop: 'Stop',
  play: 'Play test sound',
  transcribe: 'Transcribe',
  speak: 'Speak',
  input: 'Microphone',
  output: 'Output device',
  systemDefault: 'System default',
  audioHint: 'Record a short phrase, listen to the recording, then test transcription and speech.',
  downloads: 'Downloads',
  readOnly: 'Channel history is read-only to preserve its original sender and reply route.',
  working: 'Anda is working…',
  organizePrompt: 'Help me organize these thoughts: ',
  restartDaemon: 'Restart daemon',
  stopDaemon: 'Stop daemon',
  openAnda: 'Open Anda',
  serviceRunning: 'Anda service is running',
  serviceStopped: 'Anda service is not running',
  installUpdate: 'Install update and restart',
  extensionToken: 'Copy Chrome extension token',
  tokenCopied: 'Chrome extension token copied. Paste it into the extension settings.',
  quitDesktop: 'Quit Anda Desktop (service keeps running)',
  setupTitle: 'Anda is ready',
  setupDetail:
    'The anda command line is installed at {path} and shared by Anda Desktop, your terminal and the Chrome extension.',
  startAtLogin: 'Start Anda when I log in',
  ok: 'OK',
  launcherRetired: 'The Anda Bot tray is now part of Anda Desktop.',
  brewOutdated:
    'Homebrew’s anda is older than this app. Run “brew upgrade anda” to use every desktop feature.',
  restartToUpgrade: 'Anda {version} is installed. Restart the service from the tray to use it.'
}
export type Label = keyof typeof en

export const desktopMessages: Record<string, Record<Label, string>> = {
  en,
  zh_CN: {
    newChat: '新聊天',
    search: '搜索聊天',
    recent: '最近',
    projects: '项目',
    memory: '记忆',
    skills: '技能',
    bookmarks: '书签',
    automations: '自动化',
    settings: '设置',
    welcome: '今天想做些什么？',
    intro: '随时帮忙，长久记得。',
    prompt: '向 Anda 提问，或交给它一项工作…',
    addProject: '添加项目',
    noChats: '你的聊天会显示在这里。',
    archive: '归档',
    archived: '已归档聊天',
    restore: '恢复',
    pin: '置顶',
    unpin: '取消置顶',
    rename: '重命名',
    connected: '本地服务已连接',
    disconnected: '服务未连接',
    reconnect: '重新连接',
    noFolder: '未选择工作目录',
    general: '通用',
    config: 'Agent 配置',
    theme: '外观',
    language: '语言',
    system: '跟随系统',
    light: '浅色',
    dark: '深色',
    notifications: '任务通知',
    login: '登录时启动',
    runtime: '运行时',
    chooseBinary: '选择 anda 可执行文件',
    logs: '打开日志',
    save: '保存',
    cancel: '取消',
    close: '关闭',
    create: '创建',
    refresh: '刷新',
    memoryMode: '本次聊天的记忆',
    standard: '使用并保存记忆',
    noStore: '使用记忆，不保存',
    off: '关闭记忆',
    modelScope: '模型选择对当前服务生效',
    resources: '资源',
    noResources: '本次聊天的文件与输出会显示在这里。',
    loading: '正在连接本地工作空间…',
    history: '加载更早消息',
    newContent: '下方有新内容',
    unconfirmed: '一条消息可能已被受理。请核对聊天后再发送。',
    reviewed: '已核对聊天，允许发送新消息',
    local: '本地',
    update: '检查更新',
    searchHint: '搜索标题，按 Enter 搜索聊天内容',
    schedule: '计划',
    task: '任务提示',
    name: '名称',
    interval: '间隔',
    timezone: '时区',
    pause: '暂停',
    resume: '恢复',
    remove: '删除',
    noJobs: '把重复的工作交给 Anda。',
    newJob: '新建自动化',
    runHistory: '最近运行',
    nextRun: '下次运行',
    suggestion1: '探索一个项目',
    suggestion2: '整理我的想法',
    suggestion3: '查看我的记忆',
    details: '详情',
    emptySearch: '没有匹配的聊天',
    // Workbench and audio panels
    changes: '改动',
    terminal: '终端',
    browser: '浏览器',
    newTerminal: '新建终端',
    chooseProject: '选择项目目录以打开工作面板。',
    empty: '没有改动',
    staged: '已暂存',
    unstaged: '工作目录',
    stage: '暂存',
    unstage: '取消暂存',
    commit: '提交',
    message: '提交说明',
    gitHistory: '历史',
    worktrees: '工作树',
    branch: '新分支名称',
    createWorktree: '创建工作树',
    newTab: '新标签页',
    address: '地址',
    back: '后退',
    forward: '前进',
    reload: '刷新',
    find: '查找',
    open: '打开',
    audio: '音频',
    record: '测试录音',
    stop: '停止',
    play: '播放测试音',
    transcribe: '转写',
    speak: '朗读',
    input: '麦克风',
    output: '输出设备',
    systemDefault: '系统默认',
    audioHint: '录制一句话，回放确认后，再测试转写和朗读。',
    downloads: '下载',
    readOnly: '通道聊天仅供查看，避免改变原有发送者和回复路由。',
    working: 'Anda 正在处理…',
    organizePrompt: '帮我整理一下这些想法：',
    restartDaemon: '重启服务',
    stopDaemon: '停止服务',
    openAnda: '打开 Anda',
    serviceRunning: 'Anda 服务运行中',
    serviceStopped: 'Anda 服务未运行',
    installUpdate: '安装更新并重启',
    extensionToken: '复制 Chrome 扩展令牌',
    tokenCopied: 'Chrome 扩展令牌已复制，请粘贴到扩展设置中。',
    quitDesktop: '退出 Anda 桌面端（服务继续运行）',
    setupTitle: 'Anda 已准备就绪',
    setupDetail: 'anda 命令行已安装在 {path}，由 Anda 桌面端、终端和 Chrome 扩展共同使用。',
    startAtLogin: '登录时启动 Anda',
    ok: '好',
    launcherRetired: 'Anda Bot 托盘已并入 Anda 桌面端。',
    brewOutdated: 'Homebrew 安装的 anda 比本应用旧。运行“brew upgrade anda”即可使用全部桌面功能。',
    restartToUpgrade: 'Anda {version} 已安装。请从托盘重启服务以启用新版本。'
  },
  fr: {
    newChat: 'Nouvelle discussion',
    search: 'Rechercher',
    recent: 'Récents',
    projects: 'Projets',
    memory: 'Mémoire',
    skills: 'Compétences',
    bookmarks: 'Favoris',
    automations: 'Automatisations',
    settings: 'Paramètres',
    welcome: 'Que souhaitez-vous faire ?',
    intro: 'Un peu d’aide. Une mémoire durable.',
    prompt: 'Demandez à Anda ou confiez-lui une tâche…',
    addProject: 'Ajouter un projet',
    noChats: 'Vos discussions apparaîtront ici.',
    archive: 'Archiver',
    archived: 'Discussions archivées',
    restore: 'Restaurer',
    pin: 'Épingler',
    unpin: 'Désépingler',
    rename: 'Renommer',
    connected: 'Service local connecté',
    disconnected: 'Service déconnecté',
    reconnect: 'Reconnecter',
    noFolder: 'Aucun dossier',
    general: 'Général',
    config: 'Configuration de l’agent',
    theme: 'Apparence',
    language: 'Langue',
    system: 'Système',
    light: 'Clair',
    dark: 'Sombre',
    notifications: 'Notifications de tâches',
    login: 'Lancer à la connexion',
    runtime: 'Moteur',
    chooseBinary: 'Choisir l’exécutable anda',
    logs: 'Ouvrir les journaux',
    save: 'Enregistrer',
    cancel: 'Annuler',
    close: 'Fermer',
    create: 'Créer',
    refresh: 'Actualiser',
    memoryMode: 'Mémoire de cette discussion',
    standard: 'Utiliser et enregistrer',
    noStore: 'Utiliser sans enregistrer',
    off: 'Mémoire désactivée',
    modelScope: 'Le modèle s’applique à ce service',
    resources: 'Ressources',
    noResources: 'Les fichiers de cette discussion apparaîtront ici.',
    loading: 'Connexion à votre espace local…',
    history: 'Charger les messages précédents',
    newContent: 'Nouveau contenu',
    unconfirmed: 'Un message a peut-être été accepté. Vérifiez la discussion avant de renvoyer.',
    reviewed: 'Discussion vérifiée — autoriser de nouveaux messages',
    local: 'Local',
    update: 'Vérifier les mises à jour',
    searchHint: 'Recherchez un titre ou appuyez sur Entrée pour chercher dans l’historique',
    schedule: 'Planification',
    task: 'Consigne',
    name: 'Nom',
    interval: 'Intervalle',
    timezone: 'Fuseau horaire',
    pause: 'Suspendre',
    resume: 'Reprendre',
    remove: 'Supprimer',
    noJobs: 'Confiez les tâches récurrentes à Anda.',
    newJob: 'Nouvelle automatisation',
    runHistory: 'Exécutions récentes',
    nextRun: 'Prochaine exécution',
    suggestion1: 'Explorer un projet',
    suggestion2: 'Organiser mes idées',
    suggestion3: 'Voir ma mémoire',
    details: 'Détails',
    emptySearch: 'Aucune discussion trouvée',
    // Workbench and audio panels
    changes: 'Modifications',
    terminal: 'Terminal',
    browser: 'Navigateur',
    newTerminal: 'Nouveau terminal',
    chooseProject: 'Sélectionnez un dossier de projet.',
    empty: 'Aucune modification',
    staged: 'Index',
    unstaged: 'Dossier de travail',
    stage: 'Indexer',
    unstage: 'Désindexer',
    commit: 'Valider',
    message: 'Message du commit',
    gitHistory: 'Historique',
    worktrees: 'Arbres de travail',
    branch: 'Nom de branche',
    createWorktree: 'Créer un arbre',
    newTab: 'Nouvel onglet',
    address: 'Adresse',
    back: 'Précédent',
    forward: 'Suivant',
    reload: 'Recharger',
    find: 'Rechercher',
    open: 'Ouvrir',
    audio: 'Audio',
    record: 'Tester l’enregistrement',
    stop: 'Arrêter',
    play: 'Jouer un son test',
    transcribe: 'Transcrire',
    speak: 'Lire',
    input: 'Microphone',
    output: 'Sortie audio',
    systemDefault: 'Par défaut',
    audioHint: 'Enregistrez une phrase, écoutez-la, puis testez la transcription et la lecture.',
    downloads: 'Téléchargements',
    readOnly:
      'L’historique du canal est en lecture seule pour préserver l’expéditeur d’origine et la voie de réponse.',
    working: 'Anda travaille…',
    organizePrompt: 'Aide-moi à organiser ces idées : ',
    restartDaemon: 'Redémarrer le service',
    stopDaemon: 'Arrêter le service',
    openAnda: 'Ouvrir Anda',
    serviceRunning: 'Le service Anda fonctionne',
    serviceStopped: 'Le service Anda est arrêté',
    installUpdate: 'Installer la mise à jour et redémarrer',
    extensionToken: 'Copier le jeton de l’extension Chrome',
    tokenCopied: 'Jeton de l’extension Chrome copié. Collez-le dans les réglages de l’extension.',
    quitDesktop: 'Quitter Anda Desktop (le service continue)',
    setupTitle: 'Anda est prêt',
    setupDetail:
      'La ligne de commande anda est installée dans {path} et partagée par Anda Desktop, votre terminal et l’extension Chrome.',
    startAtLogin: 'Démarrer Anda à l’ouverture de session',
    ok: 'OK',
    launcherRetired: 'Le lanceur Anda Bot fait désormais partie d’Anda Desktop.',
    brewOutdated:
      'Le anda de Homebrew est plus ancien que cette app. Lancez « brew upgrade anda » pour toutes les fonctions.',
    restartToUpgrade:
      'Anda {version} est installé. Redémarrez le service depuis l’icône pour l’utiliser.'
  },
  es: {
    newChat: 'Nuevo chat',
    search: 'Buscar chats',
    recent: 'Recientes',
    projects: 'Proyectos',
    memory: 'Memoria',
    skills: 'Habilidades',
    bookmarks: 'Favoritos',
    automations: 'Automatizaciones',
    settings: 'Ajustes',
    welcome: '¿Qué te gustaría hacer?',
    intro: 'Un poco de ayuda. Una memoria duradera.',
    prompt: 'Pregunta a Anda o encárgale una tarea…',
    addProject: 'Añadir proyecto',
    noChats: 'Tus conversaciones aparecerán aquí.',
    archive: 'Archivar',
    archived: 'Chats archivados',
    restore: 'Restaurar',
    pin: 'Fijar',
    unpin: 'Desfijar',
    rename: 'Renombrar',
    connected: 'Servicio local conectado',
    disconnected: 'Servicio desconectado',
    reconnect: 'Reconectar',
    noFolder: 'Sin carpeta',
    general: 'General',
    config: 'Configuración del agente',
    theme: 'Apariencia',
    language: 'Idioma',
    system: 'Sistema',
    light: 'Claro',
    dark: 'Oscuro',
    notifications: 'Notificaciones de tareas',
    login: 'Abrir al iniciar sesión',
    runtime: 'Motor',
    chooseBinary: 'Elegir ejecutable anda',
    logs: 'Abrir registros',
    save: 'Guardar',
    cancel: 'Cancelar',
    close: 'Cerrar',
    create: 'Crear',
    refresh: 'Actualizar',
    memoryMode: 'Memoria de este chat',
    standard: 'Usar y guardar memoria',
    noStore: 'Usar sin guardar',
    off: 'Memoria desactivada',
    modelScope: 'El modelo se aplica a este servicio',
    resources: 'Recursos',
    noResources: 'Los archivos de este chat aparecerán aquí.',
    loading: 'Conectando al espacio local…',
    history: 'Cargar mensajes anteriores',
    newContent: 'Contenido nuevo',
    unconfirmed: 'Es posible que se haya aceptado un mensaje. Revisa el chat antes de reenviar.',
    reviewed: 'Chat revisado — permitir mensajes nuevos',
    local: 'Local',
    update: 'Buscar actualizaciones',
    searchHint: 'Busca títulos o pulsa Intro para buscar en el historial',
    schedule: 'Programación',
    task: 'Instrucción',
    name: 'Nombre',
    interval: 'Intervalo',
    timezone: 'Zona horaria',
    pause: 'Pausar',
    resume: 'Reanudar',
    remove: 'Eliminar',
    noJobs: 'Deja las tareas repetitivas a Anda.',
    newJob: 'Nueva automatización',
    runHistory: 'Ejecuciones recientes',
    nextRun: 'Próxima ejecución',
    suggestion1: 'Explorar un proyecto',
    suggestion2: 'Organizar mis ideas',
    suggestion3: 'Revisar mi memoria',
    details: 'Detalles',
    emptySearch: 'No hay conversaciones coincidentes',
    // Workbench and audio panels
    changes: 'Cambios',
    terminal: 'Terminal',
    browser: 'Navegador',
    newTerminal: 'Nueva terminal',
    chooseProject: 'Selecciona una carpeta de proyecto.',
    empty: 'Sin cambios',
    staged: 'Preparados',
    unstaged: 'Directorio de trabajo',
    stage: 'Preparar',
    unstage: 'Quitar',
    commit: 'Confirmar',
    message: 'Mensaje del commit',
    gitHistory: 'Historial',
    worktrees: 'Árboles de trabajo',
    branch: 'Nombre de rama',
    createWorktree: 'Crear árbol',
    newTab: 'Nueva pestaña',
    address: 'Dirección',
    back: 'Atrás',
    forward: 'Adelante',
    reload: 'Recargar',
    find: 'Buscar',
    open: 'Abrir',
    audio: 'Audio',
    record: 'Grabar prueba',
    stop: 'Detener',
    play: 'Reproducir prueba',
    transcribe: 'Transcribir',
    speak: 'Leer',
    input: 'Micrófono',
    output: 'Dispositivo de salida',
    systemDefault: 'Predeterminado',
    audioHint: 'Graba una frase, escúchala y prueba la transcripción y la voz.',
    downloads: 'Descargas',
    readOnly:
      'El historial del canal es de solo lectura para conservar el remitente original y la ruta de respuesta.',
    working: 'Anda está trabajando…',
    organizePrompt: 'Ayúdame a organizar estas ideas: ',
    restartDaemon: 'Reiniciar el servicio',
    stopDaemon: 'Detener el servicio',
    openAnda: 'Abrir Anda',
    serviceRunning: 'El servicio de Anda está en ejecución',
    serviceStopped: 'El servicio de Anda no está en ejecución',
    installUpdate: 'Instalar actualización y reiniciar',
    extensionToken: 'Copiar token de la extensión de Chrome',
    tokenCopied: 'Token de la extensión de Chrome copiado. Pégalo en los ajustes de la extensión.',
    quitDesktop: 'Salir de Anda Desktop (el servicio sigue activo)',
    setupTitle: 'Anda está listo',
    setupDetail:
      'La línea de comandos anda está instalada en {path} y la comparten Anda Desktop, tu terminal y la extensión de Chrome.',
    startAtLogin: 'Iniciar Anda al iniciar sesión',
    ok: 'Aceptar',
    launcherRetired: 'La bandeja de Anda Bot ahora forma parte de Anda Desktop.',
    brewOutdated:
      'El anda de Homebrew es más antiguo que esta app. Ejecuta «brew upgrade anda» para usar todas las funciones.',
    restartToUpgrade:
      'Anda {version} está instalado. Reinicia el servicio desde la bandeja para usarlo.'
  },
  ru: {
    newChat: 'Новый чат',
    search: 'Поиск чатов',
    recent: 'Недавние',
    projects: 'Проекты',
    memory: 'Память',
    skills: 'Навыки',
    bookmarks: 'Закладки',
    automations: 'Автоматизация',
    settings: 'Настройки',
    welcome: 'Что вы хотите сделать?',
    intro: 'Помощь сейчас. Память надолго.',
    prompt: 'Спросите Anda или поручите ей задачу…',
    addProject: 'Добавить проект',
    noChats: 'Здесь появятся ваши чаты.',
    archive: 'Архивировать',
    archived: 'Архив чатов',
    restore: 'Восстановить',
    pin: 'Закрепить',
    unpin: 'Открепить',
    rename: 'Переименовать',
    connected: 'Локальная служба подключена',
    disconnected: 'Нет подключения',
    reconnect: 'Подключить',
    noFolder: 'Папка не выбрана',
    general: 'Общие',
    config: 'Настройки агента',
    theme: 'Оформление',
    language: 'Язык',
    system: 'Системное',
    light: 'Светлое',
    dark: 'Тёмное',
    notifications: 'Уведомления о задачах',
    login: 'Запуск при входе',
    runtime: 'Среда выполнения',
    chooseBinary: 'Выбрать файл anda',
    logs: 'Открыть журналы',
    save: 'Сохранить',
    cancel: 'Отмена',
    close: 'Закрыть',
    create: 'Создать',
    refresh: 'Обновить',
    memoryMode: 'Память этого чата',
    standard: 'Использовать и сохранять',
    noStore: 'Использовать без сохранения',
    off: 'Память выключена',
    modelScope: 'Выбор модели действует для этой службы',
    resources: 'Ресурсы',
    noResources: 'Здесь появятся файлы этого чата.',
    loading: 'Подключение к локальной среде…',
    history: 'Загрузить предыдущие сообщения',
    newContent: 'Есть новые сообщения',
    unconfirmed: 'Сообщение могло быть принято. Проверьте чат перед повторной отправкой.',
    reviewed: 'Чат проверен — разрешить новые сообщения',
    local: 'Локально',
    update: 'Проверить обновления',
    searchHint: 'Поиск по заголовкам; Enter — поиск в истории',
    schedule: 'Расписание',
    task: 'Задание',
    name: 'Название',
    interval: 'Интервал',
    timezone: 'Часовой пояс',
    pause: 'Приостановить',
    resume: 'Продолжить',
    remove: 'Удалить',
    noJobs: 'Поручите повторяющиеся задачи Anda.',
    newJob: 'Новая автоматизация',
    runHistory: 'Последние запуски',
    nextRun: 'Следующий запуск',
    suggestion1: 'Изучить проект',
    suggestion2: 'Упорядочить мысли',
    suggestion3: 'Просмотреть память',
    details: 'Подробности',
    emptySearch: 'Совпадений нет',
    // Workbench and audio panels
    changes: 'Изменения',
    terminal: 'Терминал',
    browser: 'Браузер',
    newTerminal: 'Новый терминал',
    chooseProject: 'Выберите папку проекта.',
    empty: 'Нет изменений',
    staged: 'В индексе',
    unstaged: 'Рабочая папка',
    stage: 'Добавить',
    unstage: 'Убрать',
    commit: 'Коммит',
    message: 'Сообщение коммита',
    gitHistory: 'История',
    worktrees: 'Рабочие деревья',
    branch: 'Имя ветки',
    createWorktree: 'Создать дерево',
    newTab: 'Новая вкладка',
    address: 'Адрес',
    back: 'Назад',
    forward: 'Вперёд',
    reload: 'Обновить',
    find: 'Найти',
    open: 'Открыть',
    audio: 'Аудио',
    record: 'Записать тест',
    stop: 'Остановить',
    play: 'Тестовый звук',
    transcribe: 'Распознать',
    speak: 'Озвучить',
    input: 'Микрофон',
    output: 'Устройство вывода',
    systemDefault: 'По умолчанию',
    audioHint: 'Запишите фразу, прослушайте её и проверьте распознавание и синтез речи.',
    downloads: 'Загрузки',
    readOnly:
      'История канала доступна только для чтения, чтобы сохранить исходного отправителя и маршрут ответа.',
    working: 'Anda работает…',
    organizePrompt: 'Помоги мне упорядочить эти мысли: ',
    restartDaemon: 'Перезапустить службу',
    stopDaemon: 'Остановить службу',
    openAnda: 'Открыть Anda',
    serviceRunning: 'Служба Anda работает',
    serviceStopped: 'Служба Anda не запущена',
    installUpdate: 'Установить обновление и перезапустить',
    extensionToken: 'Скопировать токен расширения Chrome',
    tokenCopied: 'Токен расширения Chrome скопирован. Вставьте его в настройки расширения.',
    quitDesktop: 'Выйти из Anda Desktop (служба продолжит работу)',
    setupTitle: 'Anda готова',
    setupDetail:
      'Командная строка anda установлена в {path} и используется Anda Desktop, терминалом и расширением Chrome.',
    startAtLogin: 'Запускать Anda при входе в систему',
    ok: 'ОК',
    launcherRetired: 'Трей Anda Bot теперь входит в Anda Desktop.',
    brewOutdated:
      'anda из Homebrew старше этого приложения. Выполните «brew upgrade anda», чтобы получить все функции.',
    restartToUpgrade:
      'Anda {version} установлена. Перезапустите службу из трея, чтобы использовать её.'
  },
  ar: {
    newChat: 'محادثة جديدة',
    search: 'البحث في المحادثات',
    recent: 'الأخيرة',
    projects: 'المشاريع',
    memory: 'الذاكرة',
    skills: 'المهارات',
    bookmarks: 'الإشارات المرجعية',
    automations: 'الأتمتة',
    settings: 'الإعدادات',
    welcome: 'ماذا تريد أن تفعل؟',
    intro: 'مساعدة الآن وذاكرة تدوم.',
    prompt: 'اسأل Anda أو كلّفها بمهمة…',
    addProject: 'إضافة مشروع',
    noChats: 'ستظهر محادثاتك هنا.',
    archive: 'أرشفة',
    archived: 'المحادثات المؤرشفة',
    restore: 'استعادة',
    pin: 'تثبيت',
    unpin: 'إلغاء التثبيت',
    rename: 'إعادة تسمية',
    connected: 'الخدمة المحلية متصلة',
    disconnected: 'الخدمة غير متصلة',
    reconnect: 'إعادة الاتصال',
    noFolder: 'لم يتم اختيار مجلد',
    general: 'عام',
    config: 'إعدادات الوكيل',
    theme: 'المظهر',
    language: 'اللغة',
    system: 'النظام',
    light: 'فاتح',
    dark: 'داكن',
    notifications: 'إشعارات المهام',
    login: 'التشغيل عند تسجيل الدخول',
    runtime: 'بيئة التشغيل',
    chooseBinary: 'اختيار ملف anda التنفيذي',
    logs: 'فتح السجلات',
    save: 'حفظ',
    cancel: 'إلغاء',
    close: 'إغلاق',
    create: 'إنشاء',
    refresh: 'تحديث',
    memoryMode: 'ذاكرة هذه المحادثة',
    standard: 'استخدام الذاكرة وحفظها',
    noStore: 'استخدام دون حفظ',
    off: 'الذاكرة معطلة',
    modelScope: 'اختيار النموذج يسري على هذه الخدمة',
    resources: 'الموارد',
    noResources: 'ستظهر ملفات هذه المحادثة هنا.',
    loading: 'جارٍ الاتصال بمساحة العمل المحلية…',
    history: 'تحميل الرسائل السابقة',
    newContent: 'محتوى جديد',
    unconfirmed: 'ربما تم قبول رسالة. راجع المحادثة قبل إعادة الإرسال.',
    reviewed: 'راجعت المحادثة — السماح برسائل جديدة',
    local: 'محلي',
    update: 'البحث عن تحديثات',
    searchHint: 'ابحث في العناوين أو اضغط Enter للبحث في السجل',
    schedule: 'الجدولة',
    task: 'التعليمات',
    name: 'الاسم',
    interval: 'الفاصل الزمني',
    timezone: 'المنطقة الزمنية',
    pause: 'إيقاف مؤقت',
    resume: 'استئناف',
    remove: 'حذف',
    noJobs: 'دع Anda تتولى العمل المتكرر.',
    newJob: 'أتمتة جديدة',
    runHistory: 'عمليات التشغيل الأخيرة',
    nextRun: 'التشغيل التالي',
    suggestion1: 'استكشاف مشروع',
    suggestion2: 'تنظيم أفكاري',
    suggestion3: 'مراجعة ذاكرتي',
    details: 'التفاصيل',
    emptySearch: 'لا توجد محادثات مطابقة',
    // Workbench and audio panels
    changes: 'التغييرات',
    terminal: 'الطرفية',
    browser: 'المتصفح',
    newTerminal: 'طرفية جديدة',
    chooseProject: 'اختر مجلد مشروع.',
    empty: 'لا توجد تغييرات',
    staged: 'مُجهّز',
    unstaged: 'مجلد العمل',
    stage: 'تجهيز',
    unstage: 'إلغاء التجهيز',
    commit: 'تثبيت',
    message: 'رسالة التثبيت',
    gitHistory: 'السجل',
    worktrees: 'أشجار العمل',
    branch: 'اسم الفرع',
    createWorktree: 'إنشاء شجرة',
    newTab: 'علامة تبويب جديدة',
    address: 'العنوان',
    back: 'رجوع',
    forward: 'تقدم',
    reload: 'إعادة تحميل',
    find: 'بحث',
    open: 'فتح',
    audio: 'الصوت',
    record: 'تسجيل اختبار',
    stop: 'إيقاف',
    play: 'تشغيل صوت اختبار',
    transcribe: 'تفريغ',
    speak: 'قراءة',
    input: 'الميكروفون',
    output: 'جهاز الإخراج',
    systemDefault: 'الافتراضي',
    audioHint: 'سجّل عبارة واستمع إليها ثم اختبر التفريغ والنطق.',
    downloads: 'التنزيلات',
    readOnly: 'سجل القناة للقراءة فقط للحفاظ على المرسل الأصلي ومسار الرد.',
    working: 'Anda تعمل…',
    organizePrompt: 'ساعدني في تنظيم هذه الأفكار: ',
    restartDaemon: 'إعادة تشغيل الخدمة',
    stopDaemon: 'إيقاف الخدمة',
    openAnda: 'فتح Anda',
    serviceRunning: 'خدمة Anda قيد التشغيل',
    serviceStopped: 'خدمة Anda متوقفة',
    installUpdate: 'تثبيت التحديث وإعادة التشغيل',
    extensionToken: 'نسخ رمز إضافة Chrome',
    tokenCopied: 'تم نسخ رمز إضافة Chrome. الصقه في إعدادات الإضافة.',
    quitDesktop: 'إنهاء Anda Desktop (تستمر الخدمة في العمل)',
    setupTitle: 'Anda جاهز',
    setupDetail:
      'تم تثبيت سطر أوامر anda في {path}، ويشترك فيه Anda Desktop والطرفية وإضافة Chrome.',
    startAtLogin: 'تشغيل Anda عند تسجيل الدخول',
    ok: 'حسنًا',
    launcherRetired: 'أصبح رمز Anda Bot في شريط النظام جزءًا من Anda Desktop.',
    brewOutdated:
      'إصدار anda من Homebrew أقدم من هذا التطبيق. شغّل «brew upgrade anda» لاستخدام كل الميزات.',
    restartToUpgrade: 'تم تثبيت Anda {version}. أعد تشغيل الخدمة من شريط النظام لاستخدامه.'
  }
}
export function label(language: string, key: Label): string {
  const tag = language.toLowerCase().startsWith('zh') ? 'zh_CN' : language.replace('-', '_')
  const messages =
    desktopMessages[tag] || desktopMessages[tag.split('_')[0]!] || desktopMessages.en!
  return messages[key]
}
