import { modelSetupMessages } from './model-setup-labels'

const en = {
  ...modelSetupMessages.en!,
  newChat: 'New chat',
  search: 'Search chats',
  recent: 'Recent',
  memory: 'Memory',
  skills: 'Skills',
  bookmarks: 'Bookmarks',
  automations: 'Automations',
  settings: 'Settings',
  welcome: 'What would you like to do?',
  intro: 'A little help. A lasting memory.',
  prompt: 'Ask Anda anything, or give it something to work on…',
  noChats: 'Your conversations will appear here.',
  archive: 'Archive',
  archived: 'Archived chats',
  restore: 'Restore',
  pin: 'Pin',
  unpin: 'Unpin',
  rename: 'Rename',
  connected: 'Local daemon connected',
  disconnected: 'Daemon disconnected',
  reconnect: 'Reconnect',
  noFolder: 'No workspace',
  general: 'General',
  config: 'Agent configuration',
  theme: 'Appearance',
  language: 'Language',
  system: 'System',
  light: 'Light',
  dark: 'Dark',
  notifications: 'Task notifications',
  login: 'Launch at login',
  runtime: 'Runtime',
  chooseBinary: 'Choose anda executable',
  logs: 'Open logs',
  save: 'Save',
  cancel: 'Cancel',
  close: 'Close',
  resizeSidebar: 'Resize sidebar',
  create: 'Create',
  refresh: 'Refresh',
  modelScope: 'Model selection applies to this daemon',
  reloadModels: 'Reload models from the configuration',
  resources: 'Resources',
  noResources: 'Files and outputs from this chat will appear here.',
  loading: 'Connecting to your local workspace…',
  history: 'Load earlier messages',
  newContent: 'New content below',
  unconfirmed: 'A message may have been accepted. Review the chat before sending again.',
  reviewed: 'I reviewed the chat — allow new messages',
  update: 'Check for updates',
  desktopUpdateAvailable: 'Anda Desktop {version} available',
  desktopUpdateCheckUnavailable: 'Unable to check for desktop updates. Please try again.',
  runtimeUpToDate: 'Anda runtime {version} is up to date.',
  runtimeUpdateError: 'Anda runtime: {error}',
  runtimeUpdateKept:
    'Anda {version} stays downloaded. Install it from the tray once the release server is reachable.',
  desktopUpdateError: 'Anda Desktop: {error}',
  desktopUpToDate: 'Anda Desktop is up to date.',
  desktopUpdatesReleaseOnly: 'Desktop updates are available only in release builds.',
  desktopUpdatesManual:
    'This desktop build has no signed update channel; install the next package manually.',
  checkingUpdates: 'Checking for updates…',
  checkingRuntime: 'Checking Anda runtime updates and downloading any new release…',
  checkingDesktop: 'Checking Anda Desktop updates…',
  updateResult: 'Update result',
  updateFailed: 'Update failed',
  updateBackground:
    'You can close this dialog. The update operation will continue in the background.',
  searchHint: 'Search titles or press Enter to search conversation history',
  schedule: 'Schedule',
  task: 'Prompt',
  name: 'Name',
  interval: 'Interval',
  timezone: 'Time zone',
  pause: 'Pause',
  resume: 'Resume',
  remove: 'Remove',
  noJobs: 'Let Anda take care of the recurring work.',
  newJob: 'New automation',
  runHistory: 'Recent runs',
  nextRun: 'Next run',
  jobCompleted: 'Completed',
  suggestion1: 'Explore a project',
  suggestion2: 'Organize my thoughts',
  suggestion3: 'Review my memory',
  details: 'Details',
  emptySearch: 'No matching conversations',
  // Workbench and audio panels
  changes: 'Changes',
  terminal: 'Terminal',
  browser: 'Browser',
  newTerminal: 'New terminal',
  chooseProject: 'Select a project folder to open its workbench.',
  empty: 'No changes',
  staged: 'Staged',
  unstaged: 'Working tree',
  stage: 'Stage',
  unstage: 'Unstage',
  commit: 'Commit',
  message: 'Commit message',
  gitHistory: 'History',
  worktrees: 'Worktrees',
  branch: 'New branch name',
  createWorktree: 'Create worktree',
  newTab: 'New tab',
  address: 'Address',
  back: 'Back',
  forward: 'Forward',
  reload: 'Reload',
  find: 'Find',
  open: 'Open',
  audio: 'Audio',
  record: 'Record test',
  stop: 'Stop',
  play: 'Play test sound',
  transcribe: 'Transcribe',
  speak: 'Speak',
  input: 'Microphone',
  output: 'Output device',
  systemDefault: 'System default',
  audioHint: 'Record a short phrase, listen to the recording, then test transcription and speech.',
  downloads: 'Downloads',
  readOnly: 'Channel history is read-only to preserve its original sender and reply route.',
  working: 'Anda is working…',
  organizePrompt: 'Help me organize these thoughts: ',
  restartDaemon: 'Restart daemon',
  stopDaemon: 'Stop daemon',
  openAnda: 'Open Anda',
  serviceRunning: 'Anda service is running',
  serviceStopped: 'Anda service is not running',
  installUpdate: 'Install update and restart',
  extensionToken: 'Copy Chrome extension token',
  tokenCopied: 'Chrome extension token copied. Paste it into the extension settings.',
  quitDesktop: 'Quit Anda Desktop (service keeps running)',
  startAtLogin: 'Start Anda when I log in',
  launcherRetired: 'The Anda Bot tray is now part of Anda Desktop.',
  brewOutdated:
    'Homebrew’s anda is older than this app. Run “brew upgrade anda” to use every desktop feature.',
  restartToUpgrade: 'Anda {version} is installed. Restart the service from the tray to use it.',
  toggleSidebar: 'Toggle sidebar',
  pinned: 'Pinned',
  filterChats: 'Filter and group chats',
  groupNone: 'No grouping',
  groupDate: 'Group by date',
  groupProject: 'Group by project',
  showArchived: 'Show archived chats',
  today: 'Today',
  yesterday: 'Yesterday',
  previousWeek: 'Previous 7 days',
  previousMonth: 'Previous 30 days',
  older: 'Older',
  noProject: 'No project',
  stateApproval: 'Waiting for your approval',
  stateRunning: 'Working',
  stateFailed: 'Failed',
  stateUnread: 'Unread',
  chatActions: 'Chat actions',
  copyMarkdown: 'Copy as Markdown',
  copiedMarkdown: 'Conversation copied as Markdown.',
  revealWorkspace: 'Show folder',
  you: 'You',
  chooseFolder: 'Choose folder…',
  workspaceFor: 'Folder for this chat',
  newChatIn: 'Start a new chat in',
  recentProjects: 'Recent projects',
  chooseModel: 'Choose a model',
  tokenUsage: 'Tokens · {input} in · {output} out · {cached} cached',
  resizePanel: 'Resize panel',
  maximizePanel: 'Maximize panel',
  restorePanel: 'Restore panel size',
  revealFile: 'Show in folder',
  previewTruncated: 'showing the first 512 KB',
  binaryFile: 'Binary file — no text preview.',
  noDownload: 'This resource has no downloadable content.',
  previous: 'Previous match',
  next: 'Next match',
  startTerminal: 'Start a terminal',
  thisChat: 'This chat',
  allChanges: 'All changes',
  approvalWaiting: 'Waiting for your answer',
  moreWaiting: '+{count} more',
  answerInChat: 'Answer in chat',
  editedFiles: 'Edited {count} files',
  editedFile: 'Edited 1 file',
  turnIndex: 'Prompts in this chat',
  confirmStop: 'Stop the Anda daemon?',
  confirmStopDetail: 'Chats, automations and IM channels pause until you reconnect.',
  colorTheme: 'Theme',
  executable: 'anda executable',
  noBinary: 'No anda executable found',
  andaHome: 'Anda home',
  daemonControl: 'Service',
  modelConnection: 'Model connection',
  modelConnectionHint: 'Choose ChatGPT or an API-key provider for Anda.',
  notificationsHint: 'Notify me when a background task finishes or needs attention.',
  loginHint: 'Start Anda Desktop and the service when you log in.'
}
export type Label = keyof typeof en

export const desktopMessages: Record<string, Record<Label, string>> = {
  en,
  zh_CN: {
    ...modelSetupMessages.zh_CN!,
    newChat: '新聊天',
    search: '搜索聊天',
    recent: '最近',
    memory: '记忆',
    skills: '技能',
    bookmarks: '书签',
    automations: '自动化',
    settings: '设置',
    welcome: '今天想做些什么？',
    intro: '随时帮忙，长久记得。',
    prompt: '向 Anda 提问，或交给它一项工作…',
    noChats: '你的聊天会显示在这里。',
    archive: '归档',
    archived: '已归档聊天',
    restore: '恢复',
    pin: '置顶',
    unpin: '取消置顶',
    rename: '重命名',
    connected: '本地服务已连接',
    disconnected: '服务未连接',
    reconnect: '重新连接',
    noFolder: '未选择工作目录',
    general: '通用',
    config: 'Agent 配置',
    theme: '外观',
    language: '语言',
    system: '跟随系统',
    light: '浅色',
    dark: '深色',
    notifications: '任务通知',
    login: '登录时启动',
    runtime: '运行时',
    chooseBinary: '选择 anda 可执行文件',
    logs: '打开日志',
    save: '保存',
    cancel: '取消',
    close: '关闭',
    resizeSidebar: '调整边栏宽度',
    create: '创建',
    refresh: '刷新',
    modelScope: '模型选择对当前服务生效',
    reloadModels: '从配置重新加载模型',
    resources: '资源',
    noResources: '本次聊天的文件与输出会显示在这里。',
    loading: '正在连接本地工作空间…',
    history: '加载更早消息',
    newContent: '下方有新内容',
    unconfirmed: '一条消息可能已被受理。请核对聊天后再发送。',
    reviewed: '已核对聊天，允许发送新消息',
    update: '检查更新',
    desktopUpdateAvailable: 'Anda 桌面客户端 {version} 可更新',
    desktopUpdateCheckUnavailable: '无法检查桌面客户端更新，请重试。',
    runtimeUpToDate: 'Anda 服务 {version} 已是最新版本。',
    runtimeUpdateError: 'Anda 服务：{error}',
    runtimeUpdateKept: 'Anda {version} 的更新包仍保留在本地，发布服务器可访问后可从托盘安装。',
    desktopUpdateError: 'Anda 桌面客户端：{error}',
    desktopUpToDate: 'Anda 桌面客户端已是最新版本。',
    desktopUpdatesReleaseOnly: '当前为开发版本，桌面客户端自动更新仅适用于正式发布版本。',
    desktopUpdatesManual: '当前桌面客户端未配置签名更新通道，请手动安装新版本安装包。',
    checkingUpdates: '正在检查更新…',
    checkingRuntime: '正在检查 Anda 服务更新，如有新版本会下载到本地…',
    checkingDesktop: '正在检查 Anda 桌面客户端更新…',
    updateResult: '检查结果',
    updateFailed: '更新失败',
    updateBackground: '关闭此弹窗后，更新操作仍会在后台继续。',
    searchHint: '搜索标题，按 Enter 搜索聊天内容',
    schedule: '计划',
    task: '任务提示',
    name: '名称',
    interval: '间隔',
    timezone: '时区',
    pause: '暂停',
    resume: '恢复',
    remove: '删除',
    noJobs: '把重复的工作交给 Anda。',
    newJob: '新建自动化',
    runHistory: '最近运行',
    nextRun: '下次运行',
    jobCompleted: '已完成',
    suggestion1: '探索一个项目',
    suggestion2: '整理我的想法',
    suggestion3: '查看我的记忆',
    details: '详情',
    emptySearch: '没有匹配的聊天',
    // Workbench and audio panels
    changes: '改动',
    terminal: '终端',
    browser: '浏览器',
    newTerminal: '新建终端',
    chooseProject: '选择项目目录以打开工作面板。',
    empty: '没有改动',
    staged: '已暂存',
    unstaged: '工作目录',
    stage: '暂存',
    unstage: '取消暂存',
    commit: '提交',
    message: '提交说明',
    gitHistory: '历史',
    worktrees: '工作树',
    branch: '新分支名称',
    createWorktree: '创建工作树',
    newTab: '新标签页',
    address: '地址',
    back: '后退',
    forward: '前进',
    reload: '刷新',
    find: '查找',
    open: '打开',
    audio: '音频',
    record: '测试录音',
    stop: '停止',
    play: '播放测试音',
    transcribe: '转写',
    speak: '朗读',
    input: '麦克风',
    output: '输出设备',
    systemDefault: '系统默认',
    audioHint: '录制一句话，回放确认后，再测试转写和朗读。',
    downloads: '下载',
    readOnly: '通道聊天仅供查看，避免改变原有发送者和回复路由。',
    working: 'Anda 正在处理…',
    organizePrompt: '帮我整理一下这些想法：',
    restartDaemon: '重启服务',
    stopDaemon: '停止服务',
    openAnda: '打开 Anda',
    serviceRunning: 'Anda 服务运行中',
    serviceStopped: 'Anda 服务未运行',
    installUpdate: '安装更新并重启',
    extensionToken: '复制 Chrome 扩展令牌',
    tokenCopied: 'Chrome 扩展令牌已复制，请粘贴到扩展设置中。',
    quitDesktop: '退出 Anda 桌面端（服务继续运行）',
    startAtLogin: '登录时启动 Anda',
    launcherRetired: 'Anda Bot 托盘已并入 Anda 桌面端。',
    brewOutdated: 'Homebrew 安装的 anda 比本应用旧。运行“brew upgrade anda”即可使用全部桌面功能。',
    restartToUpgrade: 'Anda {version} 已安装。请从托盘重启服务以启用新版本。',
    toggleSidebar: '切换侧边栏',
    pinned: '已置顶',
    filterChats: '筛选与分组',
    groupNone: '不分组',
    groupDate: '按日期分组',
    groupProject: '按项目分组',
    showArchived: '显示已归档的聊天',
    today: '今天',
    yesterday: '昨天',
    previousWeek: '过去 7 天',
    previousMonth: '过去 30 天',
    older: '更早',
    noProject: '无项目',
    stateApproval: '等待你的批准',
    stateRunning: '运行中',
    stateFailed: '失败',
    stateUnread: '未读',
    chatActions: '聊天操作',
    copyMarkdown: '复制为 Markdown',
    copiedMarkdown: '已将对话复制为 Markdown。',
    revealWorkspace: '在文件夹中显示',
    you: '你',
    chooseFolder: '选择文件夹…',
    workspaceFor: '此聊天的文件夹',
    newChatIn: '在以下文件夹中新建聊天',
    recentProjects: '最近的项目',
    chooseModel: '选择模型',
    tokenUsage: 'Token · 输入 {input} · 输出 {output} · 缓存 {cached}',
    resizePanel: '调整面板大小',
    maximizePanel: '最大化面板',
    restorePanel: '恢复面板大小',
    revealFile: '在文件夹中显示',
    previewTruncated: '仅显示前 512 KB',
    binaryFile: '二进制文件，无法预览文本。',
    noDownload: '此资源没有可下载的内容。',
    previous: '上一个匹配',
    next: '下一个匹配',
    startTerminal: '启动终端',
    thisChat: '此聊天',
    allChanges: '全部更改',
    approvalWaiting: '等待你的回答',
    moreWaiting: '还有 {count} 项',
    answerInChat: '在聊天中回答',
    editedFiles: '已编辑 {count} 个文件',
    editedFile: '已编辑 1 个文件',
    turnIndex: '此聊天中的提问',
    confirmStop: '停止 Anda 服务？',
    confirmStopDetail: '聊天、自动化和 IM 渠道将暂停，直到重新连接。',
    colorTheme: '主题',
    executable: 'anda 可执行文件',
    noBinary: '未找到 anda 可执行文件',
    andaHome: 'Anda 主目录',
    daemonControl: '服务',
    modelConnection: '模型连接',
    modelConnectionHint: '为 Anda 选择 ChatGPT 或 API 密钥提供商。',
    notificationsHint: '后台任务完成或需要处理时通知我。',
    loginHint: '登录时启动 Anda Desktop 和服务。'
  },
  fr: {
    ...modelSetupMessages.fr!,
    newChat: 'Nouvelle discussion',
    search: 'Rechercher',
    recent: 'Récents',
    memory: 'Mémoire',
    skills: 'Compétences',
    bookmarks: 'Favoris',
    automations: 'Automatisations',
    settings: 'Paramètres',
    welcome: 'Que souhaitez-vous faire ?',
    intro: 'Un peu d’aide. Une mémoire durable.',
    prompt: 'Demandez à Anda ou confiez-lui une tâche…',
    noChats: 'Vos discussions apparaîtront ici.',
    archive: 'Archiver',
    archived: 'Discussions archivées',
    restore: 'Restaurer',
    pin: 'Épingler',
    unpin: 'Désépingler',
    rename: 'Renommer',
    connected: 'Service local connecté',
    disconnected: 'Service déconnecté',
    reconnect: 'Reconnecter',
    noFolder: 'Aucun dossier',
    general: 'Général',
    config: 'Configuration de l’agent',
    theme: 'Apparence',
    language: 'Langue',
    system: 'Système',
    light: 'Clair',
    dark: 'Sombre',
    notifications: 'Notifications de tâches',
    login: 'Lancer à la connexion',
    runtime: 'Moteur',
    chooseBinary: 'Choisir l’exécutable anda',
    logs: 'Ouvrir les journaux',
    save: 'Enregistrer',
    cancel: 'Annuler',
    close: 'Fermer',
    resizeSidebar: 'Redimensionner la barre latérale',
    create: 'Créer',
    refresh: 'Actualiser',
    modelScope: 'Le modèle s’applique à ce service',
    reloadModels: 'Recharger les modèles depuis la configuration',
    resources: 'Ressources',
    noResources: 'Les fichiers de cette discussion apparaîtront ici.',
    loading: 'Connexion à votre espace local…',
    history: 'Charger les messages précédents',
    newContent: 'Nouveau contenu',
    unconfirmed: 'Un message a peut-être été accepté. Vérifiez la discussion avant de renvoyer.',
    reviewed: 'Discussion vérifiée — autoriser de nouveaux messages',
    update: 'Vérifier les mises à jour',
    desktopUpdateAvailable: 'Anda Desktop {version} disponible',
    desktopUpdateCheckUnavailable:
      'Impossible de vérifier les mises à jour du bureau. Veuillez réessayer.',
    runtimeUpToDate: 'Le service Anda {version} est à jour.',
    runtimeUpdateError: 'Service Anda : {error}',
    runtimeUpdateKept:
      'Anda {version} reste téléchargé. Installez-le depuis l’icône dès que le serveur des versions est accessible.',
    desktopUpdateError: 'Anda Desktop : {error}',
    desktopUpToDate: 'Anda Desktop est à jour.',
    desktopUpdatesReleaseOnly:
      'Les mises à jour du bureau sont disponibles uniquement dans les versions publiées.',
    desktopUpdatesManual:
      'Cette version ne dispose pas de canal de mise à jour signé ; installez manuellement le prochain paquet.',
    checkingUpdates: 'Recherche de mises à jour…',
    checkingRuntime: 'Recherche et téléchargement des mises à jour du service Anda…',
    checkingDesktop: 'Recherche de mises à jour d’Anda Desktop…',
    updateResult: 'Résultat de la mise à jour',
    updateFailed: 'Échec de la mise à jour',
    updateBackground: 'Vous pouvez fermer cette fenêtre. L’opération continuera en arrière-plan.',
    searchHint: 'Recherchez un titre ou appuyez sur Entrée pour chercher dans l’historique',
    schedule: 'Planification',
    task: 'Consigne',
    name: 'Nom',
    interval: 'Intervalle',
    timezone: 'Fuseau horaire',
    pause: 'Suspendre',
    resume: 'Reprendre',
    remove: 'Supprimer',
    noJobs: 'Confiez les tâches récurrentes à Anda.',
    newJob: 'Nouvelle automatisation',
    runHistory: 'Exécutions récentes',
    nextRun: 'Prochaine exécution',
    jobCompleted: 'Terminée',
    suggestion1: 'Explorer un projet',
    suggestion2: 'Organiser mes idées',
    suggestion3: 'Voir ma mémoire',
    details: 'Détails',
    emptySearch: 'Aucune discussion trouvée',
    // Workbench and audio panels
    changes: 'Modifications',
    terminal: 'Terminal',
    browser: 'Navigateur',
    newTerminal: 'Nouveau terminal',
    chooseProject: 'Sélectionnez un dossier de projet.',
    empty: 'Aucune modification',
    staged: 'Index',
    unstaged: 'Dossier de travail',
    stage: 'Indexer',
    unstage: 'Désindexer',
    commit: 'Valider',
    message: 'Message du commit',
    gitHistory: 'Historique',
    worktrees: 'Arbres de travail',
    branch: 'Nom de branche',
    createWorktree: 'Créer un arbre',
    newTab: 'Nouvel onglet',
    address: 'Adresse',
    back: 'Précédent',
    forward: 'Suivant',
    reload: 'Recharger',
    find: 'Rechercher',
    open: 'Ouvrir',
    audio: 'Audio',
    record: 'Tester l’enregistrement',
    stop: 'Arrêter',
    play: 'Jouer un son test',
    transcribe: 'Transcrire',
    speak: 'Lire',
    input: 'Microphone',
    output: 'Sortie audio',
    systemDefault: 'Par défaut',
    audioHint: 'Enregistrez une phrase, écoutez-la, puis testez la transcription et la lecture.',
    downloads: 'Téléchargements',
    readOnly:
      'L’historique du canal est en lecture seule pour préserver l’expéditeur d’origine et la voie de réponse.',
    working: 'Anda travaille…',
    organizePrompt: 'Aide-moi à organiser ces idées : ',
    restartDaemon: 'Redémarrer le service',
    stopDaemon: 'Arrêter le service',
    openAnda: 'Ouvrir Anda',
    serviceRunning: 'Le service Anda fonctionne',
    serviceStopped: 'Le service Anda est arrêté',
    installUpdate: 'Installer la mise à jour et redémarrer',
    extensionToken: 'Copier le jeton de l’extension Chrome',
    tokenCopied: 'Jeton de l’extension Chrome copié. Collez-le dans les réglages de l’extension.',
    quitDesktop: 'Quitter Anda Desktop (le service continue)',
    startAtLogin: 'Démarrer Anda à l’ouverture de session',
    launcherRetired: 'Le lanceur Anda Bot fait désormais partie d’Anda Desktop.',
    brewOutdated:
      'Le anda de Homebrew est plus ancien que cette app. Lancez « brew upgrade anda » pour toutes les fonctions.',
    restartToUpgrade:
      'Anda {version} est installé. Redémarrez le service depuis l’icône pour l’utiliser.',
    toggleSidebar: 'Afficher/masquer la barre latérale',
    pinned: 'Épinglées',
    filterChats: 'Filtrer et grouper les discussions',
    groupNone: 'Sans regroupement',
    groupDate: 'Grouper par date',
    groupProject: 'Grouper par projet',
    showArchived: 'Afficher les discussions archivées',
    today: 'Aujourd’hui',
    yesterday: 'Hier',
    previousWeek: '7 derniers jours',
    previousMonth: '30 derniers jours',
    older: 'Plus ancien',
    noProject: 'Sans projet',
    stateApproval: 'En attente de votre approbation',
    stateRunning: 'En cours',
    stateFailed: 'Échec',
    stateUnread: 'Non lu',
    chatActions: 'Actions de la discussion',
    copyMarkdown: 'Copier en Markdown',
    copiedMarkdown: 'Discussion copiée en Markdown.',
    revealWorkspace: 'Afficher le dossier',
    you: 'Vous',
    chooseFolder: 'Choisir un dossier…',
    workspaceFor: 'Dossier de cette discussion',
    newChatIn: 'Nouvelle discussion dans',
    recentProjects: 'Projets récents',
    chooseModel: 'Choisir un modèle',
    tokenUsage: 'Jetons · {input} en entrée · {output} en sortie · {cached} en cache',
    resizePanel: 'Redimensionner le panneau',
    maximizePanel: 'Agrandir le panneau',
    restorePanel: 'Rétablir la taille du panneau',
    revealFile: 'Afficher dans le dossier',
    previewTruncated: 'seuls les 512 premiers Ko sont affichés',
    binaryFile: 'Fichier binaire — aucun aperçu texte.',
    noDownload: 'Cette ressource n’a pas de contenu téléchargeable.',
    previous: 'Résultat précédent',
    next: 'Résultat suivant',
    startTerminal: 'Ouvrir un terminal',
    thisChat: 'Cette discussion',
    allChanges: 'Toutes les modifications',
    approvalWaiting: 'En attente de votre réponse',
    moreWaiting: '+{count} de plus',
    answerInChat: 'Répondre dans la discussion',
    editedFiles: '{count} fichiers modifiés',
    editedFile: '1 fichier modifié',
    turnIndex: 'Messages de cette discussion',
    confirmStop: 'Arrêter le service Anda ?',
    confirmStopDetail:
      'Les discussions, automatisations et canaux de messagerie sont suspendus jusqu’à la reconnexion.',
    colorTheme: 'Thème',
    executable: 'exécutable anda',
    noBinary: 'Aucun exécutable anda trouvé',
    andaHome: 'Dossier Anda',
    daemonControl: 'Service',
    modelConnection: 'Connexion au modèle',
    modelConnectionHint: 'Choisissez ChatGPT ou un fournisseur avec clé API pour Anda.',
    notificationsHint:
      'M’avertir quand une tâche en arrière-plan se termine ou demande une action.',
    loginHint: 'Démarrer Anda Desktop et le service à l’ouverture de session.'
  },
  es: {
    ...modelSetupMessages.es!,
    newChat: 'Nuevo chat',
    search: 'Buscar chats',
    recent: 'Recientes',
    memory: 'Memoria',
    skills: 'Habilidades',
    bookmarks: 'Favoritos',
    automations: 'Automatizaciones',
    settings: 'Ajustes',
    welcome: '¿Qué te gustaría hacer?',
    intro: 'Un poco de ayuda. Una memoria duradera.',
    prompt: 'Pregunta a Anda o encárgale una tarea…',
    noChats: 'Tus conversaciones aparecerán aquí.',
    archive: 'Archivar',
    archived: 'Chats archivados',
    restore: 'Restaurar',
    pin: 'Fijar',
    unpin: 'Desfijar',
    rename: 'Renombrar',
    connected: 'Servicio local conectado',
    disconnected: 'Servicio desconectado',
    reconnect: 'Reconectar',
    noFolder: 'Sin carpeta',
    general: 'General',
    config: 'Configuración del agente',
    theme: 'Apariencia',
    language: 'Idioma',
    system: 'Sistema',
    light: 'Claro',
    dark: 'Oscuro',
    notifications: 'Notificaciones de tareas',
    login: 'Abrir al iniciar sesión',
    runtime: 'Motor',
    chooseBinary: 'Elegir ejecutable anda',
    logs: 'Abrir registros',
    save: 'Guardar',
    cancel: 'Cancelar',
    close: 'Cerrar',
    resizeSidebar: 'Cambiar el ancho de la barra lateral',
    create: 'Crear',
    refresh: 'Actualizar',
    modelScope: 'El modelo se aplica a este servicio',
    reloadModels: 'Recargar los modelos desde la configuración',
    resources: 'Recursos',
    noResources: 'Los archivos de este chat aparecerán aquí.',
    loading: 'Conectando al espacio local…',
    history: 'Cargar mensajes anteriores',
    newContent: 'Contenido nuevo',
    unconfirmed: 'Es posible que se haya aceptado un mensaje. Revisa el chat antes de reenviar.',
    reviewed: 'Chat revisado — permitir mensajes nuevos',
    update: 'Buscar actualizaciones',
    desktopUpdateAvailable: 'Anda Desktop {version} disponible',
    desktopUpdateCheckUnavailable:
      'No se pudieron comprobar las actualizaciones de escritorio. Inténtalo de nuevo.',
    runtimeUpToDate: 'El servicio Anda {version} está actualizado.',
    runtimeUpdateError: 'Servicio Anda: {error}',
    runtimeUpdateKept:
      'Anda {version} sigue descargado. Instálalo desde la bandeja cuando el servidor de versiones esté accesible.',
    desktopUpdateError: 'Anda Desktop: {error}',
    desktopUpToDate: 'Anda Desktop está actualizado.',
    desktopUpdatesReleaseOnly:
      'Las actualizaciones de escritorio solo están disponibles en versiones publicadas.',
    desktopUpdatesManual:
      'Esta versión no tiene un canal de actualización firmado; instala el próximo paquete manualmente.',
    checkingUpdates: 'Buscando actualizaciones…',
    checkingRuntime: 'Buscando y descargando actualizaciones del servicio Anda…',
    checkingDesktop: 'Buscando actualizaciones de Anda Desktop…',
    updateResult: 'Resultado de la actualización',
    updateFailed: 'Error de actualización',
    updateBackground: 'Puedes cerrar esta ventana. La operación continuará en segundo plano.',
    searchHint: 'Busca títulos o pulsa Intro para buscar en el historial',
    schedule: 'Programación',
    task: 'Instrucción',
    name: 'Nombre',
    interval: 'Intervalo',
    timezone: 'Zona horaria',
    pause: 'Pausar',
    resume: 'Reanudar',
    remove: 'Eliminar',
    noJobs: 'Deja las tareas repetitivas a Anda.',
    newJob: 'Nueva automatización',
    runHistory: 'Ejecuciones recientes',
    nextRun: 'Próxima ejecución',
    jobCompleted: 'Completada',
    suggestion1: 'Explorar un proyecto',
    suggestion2: 'Organizar mis ideas',
    suggestion3: 'Revisar mi memoria',
    details: 'Detalles',
    emptySearch: 'No hay conversaciones coincidentes',
    // Workbench and audio panels
    changes: 'Cambios',
    terminal: 'Terminal',
    browser: 'Navegador',
    newTerminal: 'Nueva terminal',
    chooseProject: 'Selecciona una carpeta de proyecto.',
    empty: 'Sin cambios',
    staged: 'Preparados',
    unstaged: 'Directorio de trabajo',
    stage: 'Preparar',
    unstage: 'Quitar',
    commit: 'Confirmar',
    message: 'Mensaje del commit',
    gitHistory: 'Historial',
    worktrees: 'Árboles de trabajo',
    branch: 'Nombre de rama',
    createWorktree: 'Crear árbol',
    newTab: 'Nueva pestaña',
    address: 'Dirección',
    back: 'Atrás',
    forward: 'Adelante',
    reload: 'Recargar',
    find: 'Buscar',
    open: 'Abrir',
    audio: 'Audio',
    record: 'Grabar prueba',
    stop: 'Detener',
    play: 'Reproducir prueba',
    transcribe: 'Transcribir',
    speak: 'Leer',
    input: 'Micrófono',
    output: 'Dispositivo de salida',
    systemDefault: 'Predeterminado',
    audioHint: 'Graba una frase, escúchala y prueba la transcripción y la voz.',
    downloads: 'Descargas',
    readOnly:
      'El historial del canal es de solo lectura para conservar el remitente original y la ruta de respuesta.',
    working: 'Anda está trabajando…',
    organizePrompt: 'Ayúdame a organizar estas ideas: ',
    restartDaemon: 'Reiniciar el servicio',
    stopDaemon: 'Detener el servicio',
    openAnda: 'Abrir Anda',
    serviceRunning: 'El servicio de Anda está en ejecución',
    serviceStopped: 'El servicio de Anda no está en ejecución',
    installUpdate: 'Instalar actualización y reiniciar',
    extensionToken: 'Copiar token de la extensión de Chrome',
    tokenCopied: 'Token de la extensión de Chrome copiado. Pégalo en los ajustes de la extensión.',
    quitDesktop: 'Salir de Anda Desktop (el servicio sigue activo)',
    startAtLogin: 'Iniciar Anda al iniciar sesión',
    launcherRetired: 'La bandeja de Anda Bot ahora forma parte de Anda Desktop.',
    brewOutdated:
      'El anda de Homebrew es más antiguo que esta app. Ejecuta «brew upgrade anda» para usar todas las funciones.',
    restartToUpgrade:
      'Anda {version} está instalado. Reinicia el servicio desde la bandeja para usarlo.',
    toggleSidebar: 'Mostrar u ocultar la barra lateral',
    pinned: 'Fijados',
    filterChats: 'Filtrar y agrupar chats',
    groupNone: 'Sin agrupar',
    groupDate: 'Agrupar por fecha',
    groupProject: 'Agrupar por proyecto',
    showArchived: 'Mostrar chats archivados',
    today: 'Hoy',
    yesterday: 'Ayer',
    previousWeek: 'Últimos 7 días',
    previousMonth: 'Últimos 30 días',
    older: 'Anteriores',
    noProject: 'Sin proyecto',
    stateApproval: 'Esperando tu aprobación',
    stateRunning: 'En curso',
    stateFailed: 'Error',
    stateUnread: 'No leído',
    chatActions: 'Acciones del chat',
    copyMarkdown: 'Copiar como Markdown',
    copiedMarkdown: 'Conversación copiada como Markdown.',
    revealWorkspace: 'Mostrar carpeta',
    you: 'Tú',
    chooseFolder: 'Elegir carpeta…',
    workspaceFor: 'Carpeta de este chat',
    newChatIn: 'Nuevo chat en',
    recentProjects: 'Proyectos recientes',
    chooseModel: 'Elegir un modelo',
    tokenUsage: 'Tokens · {input} de entrada · {output} de salida · {cached} en caché',
    resizePanel: 'Cambiar tamaño del panel',
    maximizePanel: 'Maximizar panel',
    restorePanel: 'Restaurar tamaño del panel',
    revealFile: 'Mostrar en la carpeta',
    previewTruncated: 'solo se muestran los primeros 512 KB',
    binaryFile: 'Archivo binario: sin vista previa de texto.',
    noDownload: 'Este recurso no tiene contenido descargable.',
    previous: 'Coincidencia anterior',
    next: 'Coincidencia siguiente',
    startTerminal: 'Abrir un terminal',
    thisChat: 'Este chat',
    allChanges: 'Todos los cambios',
    approvalWaiting: 'Esperando tu respuesta',
    moreWaiting: '+{count} más',
    answerInChat: 'Responder en el chat',
    editedFiles: '{count} archivos editados',
    editedFile: '1 archivo editado',
    turnIndex: 'Mensajes de este chat',
    confirmStop: '¿Detener el servicio de Anda?',
    confirmStopDetail:
      'Los chats, automatizaciones y canales de mensajería se pausan hasta que vuelvas a conectar.',
    colorTheme: 'Tema',
    executable: 'ejecutable anda',
    noBinary: 'No se encontró el ejecutable anda',
    andaHome: 'Carpeta de Anda',
    daemonControl: 'Servicio',
    modelConnection: 'Conexión del modelo',
    modelConnectionHint: 'Elige ChatGPT o un proveedor con clave de API para Anda.',
    notificationsHint: 'Avisarme cuando una tarea en segundo plano termine o necesite atención.',
    loginHint: 'Iniciar Anda Desktop y el servicio al iniciar sesión.'
  },
  ru: {
    ...modelSetupMessages.ru!,
    newChat: 'Новый чат',
    search: 'Поиск чатов',
    recent: 'Недавние',
    memory: 'Память',
    skills: 'Навыки',
    bookmarks: 'Закладки',
    automations: 'Автоматизация',
    settings: 'Настройки',
    welcome: 'Что вы хотите сделать?',
    intro: 'Помощь сейчас. Память надолго.',
    prompt: 'Спросите Anda или поручите ей задачу…',
    noChats: 'Здесь появятся ваши чаты.',
    archive: 'Архивировать',
    archived: 'Архив чатов',
    restore: 'Восстановить',
    pin: 'Закрепить',
    unpin: 'Открепить',
    rename: 'Переименовать',
    connected: 'Локальная служба подключена',
    disconnected: 'Нет подключения',
    reconnect: 'Подключить',
    noFolder: 'Папка не выбрана',
    general: 'Общие',
    config: 'Настройки агента',
    theme: 'Оформление',
    language: 'Язык',
    system: 'Системное',
    light: 'Светлое',
    dark: 'Тёмное',
    notifications: 'Уведомления о задачах',
    login: 'Запуск при входе',
    runtime: 'Среда выполнения',
    chooseBinary: 'Выбрать файл anda',
    logs: 'Открыть журналы',
    save: 'Сохранить',
    cancel: 'Отмена',
    close: 'Закрыть',
    resizeSidebar: 'Изменить ширину боковой панели',
    create: 'Создать',
    refresh: 'Обновить',
    modelScope: 'Выбор модели действует для этой службы',
    reloadModels: 'Перезагрузить модели из конфигурации',
    resources: 'Ресурсы',
    noResources: 'Здесь появятся файлы этого чата.',
    loading: 'Подключение к локальной среде…',
    history: 'Загрузить предыдущие сообщения',
    newContent: 'Есть новые сообщения',
    unconfirmed: 'Сообщение могло быть принято. Проверьте чат перед повторной отправкой.',
    reviewed: 'Чат проверен — разрешить новые сообщения',
    update: 'Проверить обновления',
    desktopUpdateAvailable: 'Доступна Anda Desktop {version}',
    desktopUpdateCheckUnavailable: 'Не удалось проверить обновления приложения. Повторите попытку.',
    runtimeUpToDate: 'Служба Anda {version} обновлена до последней версии.',
    runtimeUpdateError: 'Служба Anda: {error}',
    runtimeUpdateKept:
      'Anda {version} остаётся загруженной. Установите её из трея, когда сервер релизов станет доступен.',
    desktopUpdateError: 'Anda Desktop: {error}',
    desktopUpToDate: 'Anda Desktop обновлён до последней версии.',
    desktopUpdatesReleaseOnly: 'Обновления приложения доступны только в релизных сборках.',
    desktopUpdatesManual:
      'В этой сборке нет подписанного канала обновлений; установите следующий пакет вручную.',
    checkingUpdates: 'Проверка обновлений…',
    checkingRuntime: 'Проверка и загрузка обновлений службы Anda…',
    checkingDesktop: 'Проверка обновлений Anda Desktop…',
    updateResult: 'Результат обновления',
    updateFailed: 'Ошибка обновления',
    updateBackground: 'Можно закрыть это окно. Операция продолжится в фоновом режиме.',
    searchHint: 'Поиск по заголовкам; Enter — поиск в истории',
    schedule: 'Расписание',
    task: 'Задание',
    name: 'Название',
    interval: 'Интервал',
    timezone: 'Часовой пояс',
    pause: 'Приостановить',
    resume: 'Продолжить',
    remove: 'Удалить',
    noJobs: 'Поручите повторяющиеся задачи Anda.',
    newJob: 'Новая автоматизация',
    runHistory: 'Последние запуски',
    nextRun: 'Следующий запуск',
    jobCompleted: 'Выполнена',
    suggestion1: 'Изучить проект',
    suggestion2: 'Упорядочить мысли',
    suggestion3: 'Просмотреть память',
    details: 'Подробности',
    emptySearch: 'Совпадений нет',
    // Workbench and audio panels
    changes: 'Изменения',
    terminal: 'Терминал',
    browser: 'Браузер',
    newTerminal: 'Новый терминал',
    chooseProject: 'Выберите папку проекта.',
    empty: 'Нет изменений',
    staged: 'В индексе',
    unstaged: 'Рабочая папка',
    stage: 'Добавить',
    unstage: 'Убрать',
    commit: 'Коммит',
    message: 'Сообщение коммита',
    gitHistory: 'История',
    worktrees: 'Рабочие деревья',
    branch: 'Имя ветки',
    createWorktree: 'Создать дерево',
    newTab: 'Новая вкладка',
    address: 'Адрес',
    back: 'Назад',
    forward: 'Вперёд',
    reload: 'Обновить',
    find: 'Найти',
    open: 'Открыть',
    audio: 'Аудио',
    record: 'Записать тест',
    stop: 'Остановить',
    play: 'Тестовый звук',
    transcribe: 'Распознать',
    speak: 'Озвучить',
    input: 'Микрофон',
    output: 'Устройство вывода',
    systemDefault: 'По умолчанию',
    audioHint: 'Запишите фразу, прослушайте её и проверьте распознавание и синтез речи.',
    downloads: 'Загрузки',
    readOnly:
      'История канала доступна только для чтения, чтобы сохранить исходного отправителя и маршрут ответа.',
    working: 'Anda работает…',
    organizePrompt: 'Помоги мне упорядочить эти мысли: ',
    restartDaemon: 'Перезапустить службу',
    stopDaemon: 'Остановить службу',
    openAnda: 'Открыть Anda',
    serviceRunning: 'Служба Anda работает',
    serviceStopped: 'Служба Anda не запущена',
    installUpdate: 'Установить обновление и перезапустить',
    extensionToken: 'Скопировать токен расширения Chrome',
    tokenCopied: 'Токен расширения Chrome скопирован. Вставьте его в настройки расширения.',
    quitDesktop: 'Выйти из Anda Desktop (служба продолжит работу)',
    startAtLogin: 'Запускать Anda при входе в систему',
    launcherRetired: 'Трей Anda Bot теперь входит в Anda Desktop.',
    brewOutdated:
      'anda из Homebrew старше этого приложения. Выполните «brew upgrade anda», чтобы получить все функции.',
    restartToUpgrade:
      'Anda {version} установлена. Перезапустите службу из трея, чтобы использовать её.',
    toggleSidebar: 'Показать или скрыть боковую панель',
    pinned: 'Закреплённые',
    filterChats: 'Фильтр и группировка чатов',
    groupNone: 'Без группировки',
    groupDate: 'По дате',
    groupProject: 'По проекту',
    showArchived: 'Показать архивные чаты',
    today: 'Сегодня',
    yesterday: 'Вчера',
    previousWeek: 'Последние 7 дней',
    previousMonth: 'Последние 30 дней',
    older: 'Ранее',
    noProject: 'Без проекта',
    stateApproval: 'Ждёт вашего подтверждения',
    stateRunning: 'Выполняется',
    stateFailed: 'Ошибка',
    stateUnread: 'Не прочитано',
    chatActions: 'Действия с чатом',
    copyMarkdown: 'Копировать как Markdown',
    copiedMarkdown: 'Беседа скопирована как Markdown.',
    revealWorkspace: 'Показать папку',
    you: 'Вы',
    chooseFolder: 'Выбрать папку…',
    workspaceFor: 'Папка этого чата',
    newChatIn: 'Новый чат в папке',
    recentProjects: 'Недавние проекты',
    chooseModel: 'Выберите модель',
    tokenUsage: 'Токены · вход {input} · выход {output} · кэш {cached}',
    resizePanel: 'Изменить размер панели',
    maximizePanel: 'Развернуть панель',
    restorePanel: 'Восстановить размер панели',
    revealFile: 'Показать в папке',
    previewTruncated: 'показаны первые 512 КБ',
    binaryFile: 'Двоичный файл — текстовый просмотр недоступен.',
    noDownload: 'У этого ресурса нет содержимого для загрузки.',
    previous: 'Предыдущее совпадение',
    next: 'Следующее совпадение',
    startTerminal: 'Открыть терминал',
    thisChat: 'Этот чат',
    allChanges: 'Все изменения',
    approvalWaiting: 'Ждёт вашего ответа',
    moreWaiting: 'ещё {count}',
    answerInChat: 'Ответить в чате',
    editedFiles: 'Изменено файлов: {count}',
    editedFile: 'Изменён 1 файл',
    turnIndex: 'Запросы в этом чате',
    confirmStop: 'Остановить службу Anda?',
    confirmStopDetail:
      'Чаты, автоматизации и каналы сообщений будут приостановлены до переподключения.',
    colorTheme: 'Тема',
    executable: 'исполняемый файл anda',
    noBinary: 'Исполняемый файл anda не найден',
    andaHome: 'Домашняя папка Anda',
    daemonControl: 'Служба',
    modelConnection: 'Подключение модели',
    modelConnectionHint: 'Выберите ChatGPT или провайдера с API-ключом для Anda.',
    notificationsHint: 'Уведомлять, когда фоновая задача завершена или требует внимания.',
    loginHint: 'Запускать Anda Desktop и службу при входе в систему.'
  },
  ar: {
    ...modelSetupMessages.ar!,
    newChat: 'محادثة جديدة',
    search: 'البحث في المحادثات',
    recent: 'الأخيرة',
    memory: 'الذاكرة',
    skills: 'المهارات',
    bookmarks: 'الإشارات المرجعية',
    automations: 'الأتمتة',
    settings: 'الإعدادات',
    welcome: 'ماذا تريد أن تفعل؟',
    intro: 'مساعدة الآن وذاكرة تدوم.',
    prompt: 'اسأل Anda أو كلّفها بمهمة…',
    noChats: 'ستظهر محادثاتك هنا.',
    archive: 'أرشفة',
    archived: 'المحادثات المؤرشفة',
    restore: 'استعادة',
    pin: 'تثبيت',
    unpin: 'إلغاء التثبيت',
    rename: 'إعادة تسمية',
    connected: 'الخدمة المحلية متصلة',
    disconnected: 'الخدمة غير متصلة',
    reconnect: 'إعادة الاتصال',
    noFolder: 'لم يتم اختيار مجلد',
    general: 'عام',
    config: 'إعدادات الوكيل',
    theme: 'المظهر',
    language: 'اللغة',
    system: 'النظام',
    light: 'فاتح',
    dark: 'داكن',
    notifications: 'إشعارات المهام',
    login: 'التشغيل عند تسجيل الدخول',
    runtime: 'بيئة التشغيل',
    chooseBinary: 'اختيار ملف anda التنفيذي',
    logs: 'فتح السجلات',
    save: 'حفظ',
    cancel: 'إلغاء',
    close: 'إغلاق',
    resizeSidebar: 'تغيير عرض الشريط الجانبي',
    create: 'إنشاء',
    refresh: 'تحديث',
    modelScope: 'اختيار النموذج يسري على هذه الخدمة',
    reloadModels: 'إعادة تحميل النماذج من الإعدادات',
    resources: 'الموارد',
    noResources: 'ستظهر ملفات هذه المحادثة هنا.',
    loading: 'جارٍ الاتصال بمساحة العمل المحلية…',
    history: 'تحميل الرسائل السابقة',
    newContent: 'محتوى جديد',
    unconfirmed: 'ربما تم قبول رسالة. راجع المحادثة قبل إعادة الإرسال.',
    reviewed: 'راجعت المحادثة — السماح برسائل جديدة',
    update: 'البحث عن تحديثات',
    desktopUpdateAvailable: 'يتوفر Anda Desktop {version}',
    desktopUpdateCheckUnavailable: 'تعذّر البحث عن تحديثات تطبيق سطح المكتب. حاول مرة أخرى.',
    runtimeUpToDate: 'خدمة Anda {version} محدّثة.',
    runtimeUpdateError: 'خدمة Anda: {error}',
    runtimeUpdateKept:
      'يبقى Anda {version} منزّلًا. ثبّته من شريط النظام عندما يصبح خادم الإصدارات متاحًا.',
    desktopUpdateError: 'Anda Desktop: {error}',
    desktopUpToDate: 'Anda Desktop محدّث.',
    desktopUpdatesReleaseOnly: 'تحديثات تطبيق سطح المكتب متاحة فقط في الإصدارات المنشورة.',
    desktopUpdatesManual: 'لا تتضمن هذه النسخة قناة تحديث موقّعة؛ ثبّت الحزمة التالية يدويًا.',
    checkingUpdates: 'جارٍ البحث عن تحديثات…',
    checkingRuntime: 'جارٍ البحث عن تحديثات خدمة Anda وتنزيلها…',
    checkingDesktop: 'جارٍ البحث عن تحديثات Anda Desktop…',
    updateResult: 'نتيجة التحديث',
    updateFailed: 'فشل التحديث',
    updateBackground: 'يمكنك إغلاق هذه النافذة. ستستمر العملية في الخلفية.',
    searchHint: 'ابحث في العناوين أو اضغط Enter للبحث في السجل',
    schedule: 'الجدولة',
    task: 'التعليمات',
    name: 'الاسم',
    interval: 'الفاصل الزمني',
    timezone: 'المنطقة الزمنية',
    pause: 'إيقاف مؤقت',
    resume: 'استئناف',
    remove: 'حذف',
    noJobs: 'دع Anda تتولى العمل المتكرر.',
    newJob: 'أتمتة جديدة',
    runHistory: 'عمليات التشغيل الأخيرة',
    nextRun: 'التشغيل التالي',
    jobCompleted: 'مكتملة',
    suggestion1: 'استكشاف مشروع',
    suggestion2: 'تنظيم أفكاري',
    suggestion3: 'مراجعة ذاكرتي',
    details: 'التفاصيل',
    emptySearch: 'لا توجد محادثات مطابقة',
    // Workbench and audio panels
    changes: 'التغييرات',
    terminal: 'الطرفية',
    browser: 'المتصفح',
    newTerminal: 'طرفية جديدة',
    chooseProject: 'اختر مجلد مشروع.',
    empty: 'لا توجد تغييرات',
    staged: 'مُجهّز',
    unstaged: 'مجلد العمل',
    stage: 'تجهيز',
    unstage: 'إلغاء التجهيز',
    commit: 'تثبيت',
    message: 'رسالة التثبيت',
    gitHistory: 'السجل',
    worktrees: 'أشجار العمل',
    branch: 'اسم الفرع',
    createWorktree: 'إنشاء شجرة',
    newTab: 'علامة تبويب جديدة',
    address: 'العنوان',
    back: 'رجوع',
    forward: 'تقدم',
    reload: 'إعادة تحميل',
    find: 'بحث',
    open: 'فتح',
    audio: 'الصوت',
    record: 'تسجيل اختبار',
    stop: 'إيقاف',
    play: 'تشغيل صوت اختبار',
    transcribe: 'تفريغ',
    speak: 'قراءة',
    input: 'الميكروفون',
    output: 'جهاز الإخراج',
    systemDefault: 'الافتراضي',
    audioHint: 'سجّل عبارة واستمع إليها ثم اختبر التفريغ والنطق.',
    downloads: 'التنزيلات',
    readOnly: 'سجل القناة للقراءة فقط للحفاظ على المرسل الأصلي ومسار الرد.',
    working: 'Anda تعمل…',
    organizePrompt: 'ساعدني في تنظيم هذه الأفكار: ',
    restartDaemon: 'إعادة تشغيل الخدمة',
    stopDaemon: 'إيقاف الخدمة',
    openAnda: 'فتح Anda',
    serviceRunning: 'خدمة Anda قيد التشغيل',
    serviceStopped: 'خدمة Anda متوقفة',
    installUpdate: 'تثبيت التحديث وإعادة التشغيل',
    extensionToken: 'نسخ رمز إضافة Chrome',
    tokenCopied: 'تم نسخ رمز إضافة Chrome. الصقه في إعدادات الإضافة.',
    quitDesktop: 'إنهاء Anda Desktop (تستمر الخدمة في العمل)',
    startAtLogin: 'تشغيل Anda عند تسجيل الدخول',
    launcherRetired: 'أصبح رمز Anda Bot في شريط النظام جزءًا من Anda Desktop.',
    brewOutdated:
      'إصدار anda من Homebrew أقدم من هذا التطبيق. شغّل «brew upgrade anda» لاستخدام كل الميزات.',
    restartToUpgrade: 'تم تثبيت Anda {version}. أعد تشغيل الخدمة من شريط النظام لاستخدامه.',
    toggleSidebar: 'إظهار الشريط الجانبي أو إخفاؤه',
    pinned: 'المثبتة',
    filterChats: 'تصفية المحادثات وتجميعها',
    groupNone: 'دون تجميع',
    groupDate: 'التجميع حسب التاريخ',
    groupProject: 'التجميع حسب المشروع',
    showArchived: 'إظهار المحادثات المؤرشفة',
    today: 'اليوم',
    yesterday: 'أمس',
    previousWeek: 'آخر 7 أيام',
    previousMonth: 'آخر 30 يومًا',
    older: 'أقدم',
    noProject: 'دون مشروع',
    stateApproval: 'بانتظار موافقتك',
    stateRunning: 'قيد التشغيل',
    stateFailed: 'فشل',
    stateUnread: 'غير مقروءة',
    chatActions: 'إجراءات المحادثة',
    copyMarkdown: 'نسخ بتنسيق Markdown',
    copiedMarkdown: 'تم نسخ المحادثة بتنسيق Markdown.',
    revealWorkspace: 'إظهار المجلد',
    you: 'أنت',
    chooseFolder: 'اختيار مجلد…',
    workspaceFor: 'مجلد هذه المحادثة',
    newChatIn: 'بدء محادثة جديدة في',
    recentProjects: 'المشاريع الأخيرة',
    chooseModel: 'اختر نموذجًا',
    tokenUsage: 'الرموز · {input} إدخال · {output} إخراج · {cached} مخزنة',
    resizePanel: 'تغيير حجم اللوحة',
    maximizePanel: 'تكبير اللوحة',
    restorePanel: 'استعادة حجم اللوحة',
    revealFile: 'إظهار في المجلد',
    previewTruncated: 'يتم عرض أول 512 كيلوبايت فقط',
    binaryFile: 'ملف ثنائي — لا توجد معاينة نصية.',
    noDownload: 'لا يحتوي هذا المورد على محتوى قابل للتنزيل.',
    previous: 'المطابقة السابقة',
    next: 'المطابقة التالية',
    startTerminal: 'تشغيل طرفية',
    thisChat: 'هذه المحادثة',
    allChanges: 'كل التغييرات',
    approvalWaiting: 'بانتظار إجابتك',
    moreWaiting: '+{count} أخرى',
    answerInChat: 'الإجابة في المحادثة',
    editedFiles: 'تم تعديل {count} ملفات',
    editedFile: 'تم تعديل ملف واحد',
    turnIndex: 'الرسائل في هذه المحادثة',
    confirmStop: 'إيقاف خدمة Anda؟',
    confirmStopDetail: 'تتوقف المحادثات والأتمتة وقنوات المراسلة مؤقتًا حتى تعيد الاتصال.',
    colorTheme: 'السمة',
    executable: 'ملف anda التنفيذي',
    noBinary: 'لم يتم العثور على ملف anda التنفيذي',
    andaHome: 'مجلد Anda الرئيسي',
    daemonControl: 'الخدمة',
    modelConnection: 'الاتصال بالنموذج',
    modelConnectionHint: 'اختر ChatGPT أو مزودًا بمفتاح API لـ Anda.',
    notificationsHint: 'أعلمني عند انتهاء مهمة في الخلفية أو حاجتها إلى انتباهي.',
    loginHint: 'تشغيل Anda Desktop والخدمة عند تسجيل الدخول.'
  }
}
export function label(language: string, key: Label): string {
  const tag = language.toLowerCase().startsWith('zh') ? 'zh_CN' : language.replace('-', '_')
  const messages =
    desktopMessages[tag] || desktopMessages[tag.split('_')[0]!] || desktopMessages.en!
  return messages[key]
}
