const en = {
  changes: 'Changes',
  terminal: 'Terminal',
  browser: 'Browser',
  newTerminal: 'New terminal',
  chooseProject: 'Select a project folder to open its workbench.',
  empty: 'No changes',
  staged: 'Staged',
  unstaged: 'Working tree',
  stage: 'Stage',
  unstage: 'Unstage',
  commit: 'Commit',
  message: 'Commit message',
  history: 'History',
  worktrees: 'Worktrees',
  branch: 'New branch name',
  createWorktree: 'Create worktree',
  archive: 'Archive',
  restore: 'Restore',
  newTab: 'New tab',
  address: 'Address',
  back: 'Back',
  forward: 'Forward',
  reload: 'Reload',
  search: 'Find',
  close: 'Close',
  refresh: 'Refresh',
  open: 'Open',
  audio: 'Audio',
  record: 'Record test',
  stop: 'Stop',
  play: 'Play test sound',
  transcribe: 'Transcribe',
  speak: 'Speak',
  input: 'Microphone',
  output: 'Output device',
  systemDefault: 'System default',
  audioHint: 'Record a short phrase, listen to the recording, then test transcription and speech.',
  downloads: 'Downloads',
  loading: 'Loading…',
  create: 'Create',
  cancel: 'Cancel'
}
type Key = keyof typeof en
const translated: Record<string, string[]> = {
  zh: [
    '改动',
    '终端',
    '浏览器',
    '新建终端',
    '选择项目目录以打开工作面板。',
    '没有改动',
    '已暂存',
    '工作目录',
    '暂存',
    '取消暂存',
    '提交',
    '提交说明',
    '历史',
    '工作树',
    '新分支名称',
    '创建工作树',
    '归档',
    '恢复',
    '新标签页',
    '地址',
    '后退',
    '前进',
    '刷新',
    '查找',
    '关闭',
    '刷新',
    '打开',
    '音频',
    '测试录音',
    '停止',
    '播放测试音',
    '转写',
    '朗读',
    '麦克风',
    '输出设备',
    '系统默认',
    '录制一句话，回放确认后，再测试转写和朗读。',
    '下载',
    '正在加载…',
    '创建',
    '取消'
  ],
  fr: [
    'Modifications',
    'Terminal',
    'Navigateur',
    'Nouveau terminal',
    'Sélectionnez un dossier de projet.',
    'Aucune modification',
    'Index',
    'Dossier de travail',
    'Indexer',
    'Désindexer',
    'Valider',
    'Message du commit',
    'Historique',
    'Arbres de travail',
    'Nom de branche',
    'Créer un arbre',
    'Archiver',
    'Restaurer',
    'Nouvel onglet',
    'Adresse',
    'Précédent',
    'Suivant',
    'Recharger',
    'Rechercher',
    'Fermer',
    'Actualiser',
    'Ouvrir',
    'Audio',
    'Tester l’enregistrement',
    'Arrêter',
    'Jouer un son test',
    'Transcrire',
    'Lire',
    'Microphone',
    'Sortie audio',
    'Par défaut',
    'Enregistrez une phrase, écoutez-la, puis testez la transcription et la lecture.',
    'Téléchargements',
    'Chargement…',
    'Créer',
    'Annuler'
  ],
  es: [
    'Cambios',
    'Terminal',
    'Navegador',
    'Nueva terminal',
    'Selecciona una carpeta de proyecto.',
    'Sin cambios',
    'Preparados',
    'Directorio de trabajo',
    'Preparar',
    'Quitar',
    'Confirmar',
    'Mensaje del commit',
    'Historial',
    'Árboles de trabajo',
    'Nombre de rama',
    'Crear árbol',
    'Archivar',
    'Restaurar',
    'Nueva pestaña',
    'Dirección',
    'Atrás',
    'Adelante',
    'Recargar',
    'Buscar',
    'Cerrar',
    'Actualizar',
    'Abrir',
    'Audio',
    'Grabar prueba',
    'Detener',
    'Reproducir prueba',
    'Transcribir',
    'Leer',
    'Micrófono',
    'Dispositivo de salida',
    'Predeterminado',
    'Graba una frase, escúchala y prueba la transcripción y la voz.',
    'Descargas',
    'Cargando…',
    'Crear',
    'Cancelar'
  ],
  ru: [
    'Изменения',
    'Терминал',
    'Браузер',
    'Новый терминал',
    'Выберите папку проекта.',
    'Нет изменений',
    'В индексе',
    'Рабочая папка',
    'Добавить',
    'Убрать',
    'Коммит',
    'Сообщение коммита',
    'История',
    'Рабочие деревья',
    'Имя ветки',
    'Создать дерево',
    'Архивировать',
    'Восстановить',
    'Новая вкладка',
    'Адрес',
    'Назад',
    'Вперёд',
    'Обновить',
    'Найти',
    'Закрыть',
    'Обновить',
    'Открыть',
    'Аудио',
    'Записать тест',
    'Остановить',
    'Тестовый звук',
    'Распознать',
    'Озвучить',
    'Микрофон',
    'Устройство вывода',
    'По умолчанию',
    'Запишите фразу, прослушайте её и проверьте распознавание и синтез речи.',
    'Загрузки',
    'Загрузка…',
    'Создать',
    'Отмена'
  ],
  ar: [
    'التغييرات',
    'الطرفية',
    'المتصفح',
    'طرفية جديدة',
    'اختر مجلد مشروع.',
    'لا توجد تغييرات',
    'مُجهّز',
    'مجلد العمل',
    'تجهيز',
    'إلغاء التجهيز',
    'تثبيت',
    'رسالة التثبيت',
    'السجل',
    'أشجار العمل',
    'اسم الفرع',
    'إنشاء شجرة',
    'أرشفة',
    'استعادة',
    'علامة تبويب جديدة',
    'العنوان',
    'رجوع',
    'تقدم',
    'إعادة تحميل',
    'بحث',
    'إغلاق',
    'تحديث',
    'فتح',
    'الصوت',
    'تسجيل اختبار',
    'إيقاف',
    'تشغيل صوت اختبار',
    'تفريغ',
    'قراءة',
    'الميكروفون',
    'جهاز الإخراج',
    'الافتراضي',
    'سجّل عبارة واستمع إليها ثم اختبر التفريغ والنطق.',
    'التنزيلات',
    'جارٍ التحميل…',
    'إنشاء',
    'إلغاء'
  ]
}
export const workbenchMessages: Record<string, Record<Key, string>> = { en }
for (const [language, values] of Object.entries(translated)) {
  if (values.length !== Object.keys(en).length)
    throw new Error(`Incomplete workbench translation: ${language}`)
  workbenchMessages[language] = Object.fromEntries(
    Object.keys(en).map((key, i) => [key, values[i]])
  ) as Record<Key, string>
}
export function wb(language: string, key: Key): string {
  return (workbenchMessages[language.split(/[-_]/)[0]] || en)[key]
}
