package cmd

import (
	"encoding/base64"
	"fmt"
	"os"
	"time"

	"github.com/ldclabs/cose/cose"
	"github.com/ldclabs/cose/cwt"
	"github.com/ldclabs/cose/iana"
	"github.com/ldclabs/cose/key"
	"github.com/ldclabs/cose/key/ed25519"
	"github.com/spf13/cobra"
)

var cwtCmd = &cobra.Command{
	Use:   "cwt",
	Short: "Create a CWT (CBOR Web Token)",
	Long: `Create and sign a CWT using an Ed25519 private key.
The private key should be base64url-encoded CBOR (COSE Key format),
as generated by the 'keygen' command.

Example:
  anda-cli cwt --key <base64url_private_key> --subject <user_id> --audience <space_id> --scope write
  anda-cli cwt --key <base64url_private_key> --subject <user_id> --audience "*" --scope "*" --expiration 3600`,
	Run: func(cmd *cobra.Command, args []string) {
		keyB64, _ := cmd.Flags().GetString("key")
		subject, _ := cmd.Flags().GetString("subject")
		audience, _ := cmd.Flags().GetString("audience")
		scope, _ := cmd.Flags().GetString("scope")
		issuer, _ := cmd.Flags().GetString("issuer")
		expSec, _ := cmd.Flags().GetInt64("expiration")

		if keyB64 == "" {
			exitError(fmt.Errorf("--key is required"))
		}
		if subject == "" {
			exitError(fmt.Errorf("--subject is required"))
		}
		if audience == "" {
			exitError(fmt.Errorf("--audience is required"))
		}

		// Decode private key from base64url CBOR
		keyData, err := base64.RawURLEncoding.DecodeString(keyB64)
		if err != nil {
			exitError(fmt.Errorf("decode private key: %w", err))
		}

		var privKey key.Key
		if err := key.UnmarshalCBOR(keyData, &privKey); err != nil {
			exitError(fmt.Errorf("unmarshal private key: %w", err))
		}

		if err := ed25519.CheckKey(privKey); err != nil {
			exitError(fmt.Errorf("invalid Ed25519 key: %w", err))
		}

		signer, err := privKey.Signer()
		if err != nil {
			exitError(fmt.Errorf("create signer: %w", err))
		}

		now := time.Now()
		if expSec <= 0 {
			expSec = 3600 // default 1 hour
		}

		claims := cwt.ClaimsMap{
			iana.CWTClaimSub:   subject,
			iana.CWTClaimAud:   audience,
			iana.CWTClaimExp:   uint64(now.Unix()) + uint64(expSec),
			iana.CWTClaimIat:   uint64(now.Unix()),
			iana.CWTClaimScope: scope,
		}
		if issuer != "" {
			claims[iana.CWTClaimIss] = issuer
		}

		msg := &cose.Sign1Message[cwt.ClaimsMap]{Payload: claims}
		cwtData, err := msg.SignAndEncode(signer, nil)
		if err != nil {
			exitError(fmt.Errorf("sign CWT: %w", err))
		}

		tokenB64 := base64.RawURLEncoding.EncodeToString(cwtData)

		outputJSON, _ := cmd.Flags().GetBool("json")
		if outputJSON {
			printJSON(map[string]any{
				"token":      tokenB64,
				"subject":    subject,
				"audience":   audience,
				"scope":      scope,
				"issued_at":  now.Unix(),
				"expiration": now.Unix() + expSec,
			})
		} else {
			fmt.Printf("Token:      %s\n", tokenB64)
			fmt.Printf("Subject:    %s\n", subject)
			fmt.Printf("Audience:   %s\n", audience)
			fmt.Printf("Scope:      %s\n", scope)
			fmt.Printf("Issued At:  %s\n", now.UTC().Format(time.RFC3339))
			fmt.Printf("Expires At: %s\n", now.Add(time.Duration(expSec)*time.Second).UTC().Format(time.RFC3339))
		}
	},
}

func init() {
	cwtCmd.Flags().String("key", os.Getenv("ANDA_CWT_KEY"), "Ed25519 private key as base64url-encoded CBOR (env: ANDA_CWT_KEY)")
	cwtCmd.Flags().String("subject", os.Getenv("ANDA_CWT_SUBJECT"), "Subject claim - user/principal ID (env: ANDA_CWT_SUBJECT)")
	cwtCmd.Flags().String("audience", os.Getenv("ANDA_CWT_AUDIENCE"), "Audience claim - space ID or '*' (env: ANDA_CWT_AUDIENCE)")
	cwtCmd.Flags().String("scope", envOrDefault("ANDA_CWT_SCOPE", "read"), "Scope claim: read, write, * (env: ANDA_CWT_SCOPE)")
	cwtCmd.Flags().String("issuer", os.Getenv("ANDA_CWT_ISSUER"), "Issuer claim (env: ANDA_CWT_ISSUER)")
	cwtCmd.Flags().Int64("expiration", 3600, "Token expiration in seconds (default: 3600)")
	cwtCmd.Flags().Bool("json", false, "Output in JSON format")
	rootCmd.AddCommand(cwtCmd)
}
