name: Test
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/setup-protoc@v3
      - name: Run tests
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends -o Acquire::Retries=3 libasound2-dev
          rustup update --no-self-update stable
          cargo clippy --all-targets --all-features
          cargo test --workspace -- --nocapture
